-- STAGING ONLY. Do not move into supabase/migrations until issue #342 staging gates pass.
-- Immutable TR/EN dictionary releases with deterministic SHA-256, active pointers and rollback audit.
-- Existing runtime keeps current behavior until an active release exists for a language.

create table if not exists public.dictionary_releases_v1 (
  release_id uuid primary key default gen_random_uuid(),
  release_key text not null unique,
  language text not null check (language in ('tr','en')),
  checksum_sha256 text not null check (checksum_sha256 ~ '^[0-9a-f]{64}$'),
  word_count integer not null check (word_count > 0),
  words text[] not null,
  source_manifest jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid,
  constraint dictionary_release_words_count_check check (cardinality(words)=word_count),
  constraint dictionary_release_language_checksum_unique unique(language,checksum_sha256)
);

create table if not exists public.dictionary_release_state_v1 (
  language text primary key check (language in ('tr','en')),
  active_release_id uuid not null references public.dictionary_releases_v1(release_id) on delete restrict,
  activated_at timestamptz not null default now(),
  activated_by uuid
);

create table if not exists public.dictionary_release_events_v1 (
  id bigint generated by default as identity primary key,
  language text not null check (language in ('tr','en')),
  action text not null check (action in ('create','activate','rollback')),
  release_id uuid not null references public.dictionary_releases_v1(release_id) on delete restrict,
  previous_release_id uuid references public.dictionary_releases_v1(release_id) on delete restrict,
  actor_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.dictionary_releases_v1 enable row level security;
alter table public.dictionary_release_state_v1 enable row level security;
alter table public.dictionary_release_events_v1 enable row level security;

revoke all on public.dictionary_releases_v1 from public,anon,authenticated;
revoke all on public.dictionary_release_state_v1 from public,anon,authenticated;
revoke all on public.dictionary_release_events_v1 from public,anon,authenticated;

grant select on public.dictionary_releases_v1 to authenticated,service_role;
grant select on public.dictionary_release_state_v1 to authenticated,service_role;
grant select on public.dictionary_release_events_v1 to service_role;

-- Authenticated clients may only read the active immutable snapshot for each language.
drop policy if exists dictionary_release_active_read_v1 on public.dictionary_releases_v1;
create policy dictionary_release_active_read_v1
on public.dictionary_releases_v1
for select
to authenticated
using (
  exists (
    select 1
    from public.dictionary_release_state_v1 s
    where s.language=dictionary_releases_v1.language
      and s.active_release_id=dictionary_releases_v1.release_id
  )
);

drop policy if exists dictionary_release_state_read_v1 on public.dictionary_release_state_v1;
create policy dictionary_release_state_read_v1
on public.dictionary_release_state_v1
for select
to authenticated
using (true);

create or replace function public.prevent_dictionary_release_mutation_v1()
returns trigger
language plpgsql
set search_path=''
as $$
begin
  raise exception 'dictionary_release_immutable';
end
$$;

revoke all on function public.prevent_dictionary_release_mutation_v1() from public,anon,authenticated;

drop trigger if exists dictionary_release_immutable_v1 on public.dictionary_releases_v1;
create trigger dictionary_release_immutable_v1
before update or delete on public.dictionary_releases_v1
for each row execute function public.prevent_dictionary_release_mutation_v1();

-- Deterministic release build. The checksum contract is the UTF-8 SHA-256 of sorted distinct
-- words encoded as one `byteLength:word` entry per line. This avoids delimiter ambiguity and is
-- reproduced by the Android release-cache coordinator.
create or replace function public.admin_create_dictionary_release_v1(p_language text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_lang text := lower(trim(coalesce(p_language,'')));
  v_words text[];
  v_word_count integer;
  v_checksum text;
  v_release public.dictionary_releases_v1%rowtype;
  v_manifest jsonb;
  v_sync public.dictionary_sync_state%rowtype;
  v_missing_source integer := 0;
begin
  if v_uid is null or not public.is_admin() then raise exception 'admin_required'; end if;
  if v_lang not in ('tr','en') then raise exception 'invalid_language'; end if;

  select * into v_sync
  from public.dictionary_sync_state
  where language=v_lang;
  if not found or not coalesce(v_sync.ready,false) then raise exception 'dictionary_not_ready'; end if;

  with eligible as (
    select distinct d.normalized_word
    from public.dictionary_words d
    where d.language=v_lang
      and d.active
      and coalesce(d.game_allowed,true)
      and not coalesce(d.is_abbreviation,false)
      and not coalesce(d.is_proper_noun,false)
      and coalesce(d.lexical_kind,'word') not in ('abbreviation','acronym','code','symbol','proper_noun','synthetic_pair')
      and char_length(d.normalized_word) between 2 and 15
      and not (v_lang='tr' and right(d.normalized_word,1)='ğ')
  ), ordered as (
    select normalized_word
    from eligible
    order by normalized_word collate "C"
  )
  select
    array_agg(normalized_word order by normalized_word collate "C"),
    count(*)::integer,
    encode(
      digest(
        convert_to(
          string_agg(
            octet_length(convert_to(normalized_word,'UTF8'))::text || ':' || normalized_word,
            E'\n' order by normalized_word collate "C"
          ),
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    )
  into v_words,v_word_count,v_checksum
  from ordered;

  if coalesce(v_word_count,0)=0 or v_words is null or v_checksum is null then
    raise exception 'dictionary_release_empty';
  end if;

  select count(*)::integer into v_missing_source
  from public.dictionary_words d
  where d.language=v_lang
    and d.normalized_word=any(v_words)
    and (nullif(trim(d.source_id),'') is null or nullif(trim(d.source_version),'') is null);
  if v_missing_source>0 then raise exception 'dictionary_source_provenance_missing:%',v_missing_source; end if;

  select jsonb_build_object(
    'sync_state',jsonb_build_object(
      'ready',v_sync.ready,
      'reported_word_count',v_sync.word_count,
      'source_name',v_sync.source_name,
      'source_url',v_sync.source_url,
      'license_note',v_sync.license_note,
      'synced_at',v_sync.synced_at
    ),
    'sources',coalesce((
      select jsonb_agg(
        jsonb_build_object('source_id',q.source_id,'source_version',q.source_version)
        order by q.source_id collate "C",q.source_version collate "C"
      )
      from (
        select distinct d.source_id,d.source_version
        from public.dictionary_words d
        where d.language=v_lang and d.normalized_word=any(v_words)
      ) q
    ),'[]'::jsonb),
    'eligibility',jsonb_build_object(
      'min_length',2,
      'max_length',15,
      'active_required',true,
      'game_allowed_required',true,
      'abbreviations_allowed',false,
      'proper_nouns_allowed',false,
      'synthetic_pairs_allowed',false,
      'turkish_terminal_soft_g_allowed',false
    ),
    'checksum_format','sha256(sorted_distinct_utf8_byte_length_prefixed_lines_v1)'
  ) into v_manifest;

  select * into v_release
  from public.dictionary_releases_v1
  where language=v_lang and checksum_sha256=v_checksum;

  if found then
    return jsonb_build_object(
      'created',false,
      'release_id',v_release.release_id,
      'release_key',v_release.release_key,
      'language',v_release.language,
      'checksum_sha256',v_release.checksum_sha256,
      'word_count',v_release.word_count,
      'source_manifest',v_release.source_manifest,
      'created_at',v_release.created_at
    );
  end if;

  insert into public.dictionary_releases_v1(
    release_key,language,checksum_sha256,word_count,words,source_manifest,created_by
  ) values (
    v_lang || '-' || left(v_checksum,20),v_lang,v_checksum,v_word_count,v_words,v_manifest,v_uid
  ) returning * into v_release;

  insert into public.dictionary_release_events_v1(
    language,action,release_id,actor_id,details
  ) values (
    v_lang,'create',v_release.release_id,v_uid,
    jsonb_build_object('checksum_sha256',v_checksum,'word_count',v_word_count)
  );

  return jsonb_build_object(
    'created',true,
    'release_id',v_release.release_id,
    'release_key',v_release.release_key,
    'language',v_release.language,
    'checksum_sha256',v_release.checksum_sha256,
    'word_count',v_release.word_count,
    'source_manifest',v_release.source_manifest,
    'created_at',v_release.created_at
  );
end
$$;

revoke all on function public.admin_create_dictionary_release_v1(text) from public,anon,service_role;
grant execute on function public.admin_create_dictionary_release_v1(text) to authenticated;

create or replace function public.admin_activate_dictionary_release_v1(p_release_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_release public.dictionary_releases_v1%rowtype;
  v_previous uuid;
begin
  if v_uid is null or not public.is_admin() then raise exception 'admin_required'; end if;
  select * into v_release from public.dictionary_releases_v1 where release_id=p_release_id;
  if not found then raise exception 'release_not_found'; end if;

  select active_release_id into v_previous
  from public.dictionary_release_state_v1
  where language=v_release.language
  for update;

  insert into public.dictionary_release_state_v1(language,active_release_id,activated_at,activated_by)
  values(v_release.language,v_release.release_id,now(),v_uid)
  on conflict(language) do update
  set active_release_id=excluded.active_release_id,activated_at=now(),activated_by=v_uid;

  insert into public.dictionary_release_events_v1(
    language,action,release_id,previous_release_id,actor_id,details
  ) values (
    v_release.language,'activate',v_release.release_id,v_previous,v_uid,
    jsonb_build_object('checksum_sha256',v_release.checksum_sha256,'word_count',v_release.word_count)
  );

  return jsonb_build_object(
    'success',true,'language',v_release.language,'active_release_id',v_release.release_id,
    'previous_release_id',v_previous,'checksum_sha256',v_release.checksum_sha256,'word_count',v_release.word_count
  );
end
$$;

revoke all on function public.admin_activate_dictionary_release_v1(uuid) from public,anon,service_role;
grant execute on function public.admin_activate_dictionary_release_v1(uuid) to authenticated;

create or replace function public.admin_rollback_dictionary_release_v1(p_language text,p_release_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_uid uuid := auth.uid();
  v_lang text := lower(trim(coalesce(p_language,'')));
  v_release public.dictionary_releases_v1%rowtype;
  v_previous uuid;
begin
  if v_uid is null or not public.is_admin() then raise exception 'admin_required'; end if;
  if v_lang not in ('tr','en') then raise exception 'invalid_language'; end if;

  select * into v_release
  from public.dictionary_releases_v1
  where release_id=p_release_id and language=v_lang;
  if not found then raise exception 'release_not_found_for_language'; end if;

  select active_release_id into v_previous
  from public.dictionary_release_state_v1
  where language=v_lang
  for update;
  if v_previous is null then raise exception 'active_release_missing'; end if;
  if v_previous=p_release_id then raise exception 'release_already_active'; end if;

  update public.dictionary_release_state_v1
  set active_release_id=p_release_id,activated_at=now(),activated_by=v_uid
  where language=v_lang;

  insert into public.dictionary_release_events_v1(
    language,action,release_id,previous_release_id,actor_id,details
  ) values (
    v_lang,'rollback',p_release_id,v_previous,v_uid,
    jsonb_build_object('checksum_sha256',v_release.checksum_sha256,'word_count',v_release.word_count)
  );

  return jsonb_build_object(
    'success',true,'language',v_lang,'active_release_id',p_release_id,
    'previous_release_id',v_previous,'checksum_sha256',v_release.checksum_sha256,'word_count',v_release.word_count
  );
end
$$;

revoke all on function public.admin_rollback_dictionary_release_v1(text,uuid) from public,anon,service_role;
grant execute on function public.admin_rollback_dictionary_release_v1(text,uuid) to authenticated;

create or replace function public.get_dictionary_release_meta_v1(p_language text default 'tr')
returns table(
  language text,
  release_id uuid,
  release_key text,
  checksum_sha256 text,
  word_count integer,
  created_at timestamptz
)
language plpgsql
stable
set search_path to 'pg_catalog','public','pg_temp'
as $$
declare
  v_lang text := lower(coalesce(p_language,''));
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if v_lang not in ('tr','en') then raise exception 'invalid_language'; end if;

  return query
  select r.language,r.release_id,r.release_key,r.checksum_sha256,r.word_count,r.created_at
  from public.dictionary_release_state_v1 s
  join public.dictionary_releases_v1 r on r.release_id=s.active_release_id
  where s.language=v_lang and r.language=v_lang;
end
$$;

revoke all on function public.get_dictionary_release_meta_v1(text) from public,anon;
grant execute on function public.get_dictionary_release_meta_v1(text) to authenticated,service_role;

-- Preserve the current V4 surface. Before the first activation, this is byte-for-behavior fallback
-- to dictionary_words. Once a release is active, the immutable snapshot becomes the source of truth.
create or replace function public.get_dictionary_snapshot_v4(p_language text default 'tr')
returns table(language text,words text[])
language plpgsql
stable
set search_path to 'pg_catalog','public','pg_temp'
as $$
declare
  v_lang text := lower(coalesce(p_language,''));
  v_release_words text[];
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if v_lang not in ('tr','en') then raise exception 'invalid_language'; end if;

  select r.words into v_release_words
  from public.dictionary_release_state_v1 s
  join public.dictionary_releases_v1 r on r.release_id=s.active_release_id
  where s.language=v_lang and r.language=v_lang;

  if v_release_words is not null then
    return query select v_lang,v_release_words;
    return;
  end if;

  return query
  select v_lang,
         coalesce(array_agg(d.normalized_word order by d.normalized_word),array[]::text[])
  from public.dictionary_words d
  where d.language=v_lang
    and d.active
    and coalesce(d.game_allowed,true)
    and not coalesce(d.is_abbreviation,false)
    and not coalesce(d.is_proper_noun,false)
    and coalesce(d.lexical_kind,'word') not in ('abbreviation','acronym','code','symbol','proper_noun','synthetic_pair')
    and char_length(d.normalized_word) between 2 and 15
    and not (v_lang='tr' and right(d.normalized_word,1)='ğ');
end
$$;

revoke all on function public.get_dictionary_snapshot_v4(text) from public,anon;
grant execute on function public.get_dictionary_snapshot_v4(text) to authenticated,service_role;

-- Keep the existing v2 name so all current online clients remain compatible. Active releases cap
-- authoritative play at the same 2..15 rules as the snapshot; before activation, legacy behavior
-- remains unchanged.
create or replace function public.validate_game_word_v2(p_word text,p_language text default 'tr')
returns table(valid boolean,reason text,normalized_word text,first_letter text,last_letter text,char_length integer)
language plpgsql
stable
set search_path to 'pg_catalog','public','pg_temp'
as $$
declare
  v_lang text := lower(coalesce(p_language,''));
  v_norm text;
  v_release_words text[];
  d public.dictionary_words%rowtype;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if v_lang not in ('tr','en') then
    return query select false,'invalid_language'::text,''::text,''::text,''::text,0;
    return;
  end if;

  v_norm := public.normalize_game_word(v_lang,coalesce(p_word,''));

  select r.words into v_release_words
  from public.dictionary_release_state_v1 s
  join public.dictionary_releases_v1 r on r.release_id=s.active_release_id
  where s.language=v_lang and r.language=v_lang;

  if v_release_words is not null then
    if char_length(v_norm)<2 or char_length(v_norm)>15 then
      return query select false,'invalid_length'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
      return;
    end if;
    if (v_lang='tr' and v_norm !~ '^[a-zçğıöşü]+$') or (v_lang='en' and v_norm !~ '^[a-z]+$') then
      return query select false,'invalid_characters'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
      return;
    end if;
    if v_lang='tr' and right(v_norm,1)='ğ' then
      return query select false,'ends_with_soft_g'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
      return;
    end if;
    if not (v_norm=any(v_release_words)) then
      return query select false,'not_in_dictionary'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
      return;
    end if;
    return query select true,'valid'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;

  -- Exact legacy fallback until the first release is activated.
  if char_length(v_norm)<2 or char_length(v_norm)>30 then
    return query select false,'invalid_length'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;
  if (v_lang='tr' and v_norm !~ '^[a-zçğıöşü]+$') or (v_lang='en' and v_norm !~ '^[a-z]+$') then
    return query select false,'invalid_characters'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;

  select * into d
  from public.dictionary_words x
  where x.language=v_lang and x.normalized_word=v_norm and x.active
  limit 1;

  if d.id is null then
    return query select false,'not_in_dictionary'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;
  if coalesce(d.is_abbreviation,false) or coalesce(d.lexical_kind,'word') in ('abbreviation','acronym','code','symbol') then
    return query select false,'abbreviation_not_allowed'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;
  if coalesce(d.is_proper_noun,false) or coalesce(d.lexical_kind,'word')='proper_noun' then
    return query select false,'proper_noun_not_allowed'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;
  if not coalesce(d.game_allowed,true) or coalesce(d.lexical_kind,'word')='synthetic_pair' then
    return query select false,'not_game_allowed'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;
  if v_lang='tr' and right(v_norm,1)='ğ' then
    return query select false,'ends_with_soft_g'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
    return;
  end if;

  return query select true,'valid'::text,v_norm,left(v_norm,1),right(v_norm,1),char_length(v_norm);
end
$$;

revoke all on function public.validate_game_word_v2(text,text) from public,anon;
grant execute on function public.validate_game_word_v2(text,text) to authenticated,service_role;
