-- Competition & Social v1
-- Clubs (max 30), weekly club contribution, weekly tournament, rating leagues.
-- All competitive entry is free; rewards are earned, never purchased.

create or replace function public.league_for_rating_v1(p_rating integer)
returns text
language sql
immutable
set search_path=public,pg_temp
as $$
  select case
    when coalesce(p_rating,1000) >= 1800 then 'EFSANE'
    when coalesce(p_rating,1000) >= 1600 then 'ELMAS'
    when coalesce(p_rating,1000) >= 1400 then 'PLATİN'
    when coalesce(p_rating,1000) >= 1250 then 'ALTIN'
    when coalesce(p_rating,1000) >= 1100 then 'GÜMÜŞ'
    else 'BRONZ'
  end
$$;

create table if not exists public.clubs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  tag text not null,
  description text not null default '',
  owner_id uuid not null references public.profiles(id) on delete restrict,
  max_members integer not null default 30 check (max_members between 2 and 30),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(btrim(name)) between 3 and 24),
  check (char_length(btrim(tag)) between 2 and 6),
  check (char_length(description) <= 180)
);
create unique index if not exists clubs_name_lower_uq on public.clubs(lower(btrim(name)));
create unique index if not exists clubs_tag_upper_uq on public.clubs(upper(btrim(tag)));
create index if not exists clubs_owner_idx on public.clubs(owner_id);

create table if not exists public.club_members (
  club_id uuid not null references public.clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','moderator','member')),
  joined_at timestamptz not null default now(),
  primary key (club_id,user_id),
  unique (user_id)
);
create index if not exists club_members_club_joined_idx on public.club_members(club_id,joined_at);

create table if not exists public.club_messages (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.clubs(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 300),
  created_at timestamptz not null default now()
);
create index if not exists club_messages_club_created_idx on public.club_messages(club_id,created_at desc);

create table if not exists public.club_point_events (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.clubs(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  room_id uuid not null references public.game_rooms(id) on delete cascade,
  points integer not null check (points between 0 and 50),
  created_at timestamptz not null default now(),
  unique (room_id,user_id)
);
create index if not exists club_point_events_club_created_idx on public.club_point_events(club_id,created_at desc);

create table if not exists public.weekly_tournaments (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique,
  name text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.weekly_tournament_entries (
  tournament_id uuid not null references public.weekly_tournaments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key(tournament_id,user_id)
);
create index if not exists weekly_tournament_entries_joined_idx on public.weekly_tournament_entries(tournament_id,joined_at);

create table if not exists public.weekly_tournament_match_events (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null references public.weekly_tournaments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  room_id uuid not null references public.game_rooms(id) on delete cascade,
  points integer not null check(points between 0 and 10),
  won boolean not null default false,
  created_at timestamptz not null default now(),
  unique(tournament_id,room_id,user_id)
);
create index if not exists weekly_tournament_events_rank_idx
  on public.weekly_tournament_match_events(tournament_id,user_id,created_at);

create table if not exists public.weekly_tournament_reward_claims (
  tournament_id uuid not null references public.weekly_tournaments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  final_rank integer not null,
  reward_coins integer not null check(reward_coins >= 0),
  claimed_at timestamptz not null default now(),
  primary key(tournament_id,user_id)
);

alter table public.clubs enable row level security;
alter table public.club_members enable row level security;
alter table public.club_messages enable row level security;
alter table public.club_point_events enable row level security;
alter table public.weekly_tournaments enable row level security;
alter table public.weekly_tournament_entries enable row level security;
alter table public.weekly_tournament_match_events enable row level security;
alter table public.weekly_tournament_reward_claims enable row level security;

revoke all on public.clubs from anon;
revoke all on public.club_members from anon;
revoke all on public.club_messages from anon;
revoke all on public.club_point_events from anon;
revoke all on public.weekly_tournaments from anon;
revoke all on public.weekly_tournament_entries from anon;
revoke all on public.weekly_tournament_match_events from anon;
revoke all on public.weekly_tournament_reward_claims from anon;

revoke all on public.clubs from authenticated;
revoke all on public.club_members from authenticated;
revoke all on public.club_messages from authenticated;
revoke all on public.club_point_events from authenticated;
revoke all on public.weekly_tournaments from authenticated;
revoke all on public.weekly_tournament_entries from authenticated;
revoke all on public.weekly_tournament_match_events from authenticated;
revoke all on public.weekly_tournament_reward_claims from authenticated;

grant select on public.clubs to authenticated;
grant select on public.club_members to authenticated;
grant select,insert,delete on public.club_messages to authenticated;

drop policy if exists clubs_read_authenticated on public.clubs;
create policy clubs_read_authenticated on public.clubs for select to authenticated using (true);
drop policy if exists club_members_read_authenticated on public.club_members;
create policy club_members_read_authenticated on public.club_members for select to authenticated using (true);

drop policy if exists club_messages_read_members on public.club_messages;
create policy club_messages_read_members
on public.club_messages for select to authenticated
using (
  exists (
    select 1 from public.club_members cm
    where cm.club_id=club_messages.club_id and cm.user_id=(select auth.uid())
  )
);
drop policy if exists club_messages_insert_members on public.club_messages;
create policy club_messages_insert_members
on public.club_messages for insert to authenticated
with check (
  sender_id=(select auth.uid())
  and exists (
    select 1 from public.club_members cm
    where cm.club_id=club_messages.club_id and cm.user_id=(select auth.uid())
  )
  and char_length(btrim(body)) between 1 and 300
);
drop policy if exists club_messages_delete_own on public.club_messages;
create policy club_messages_delete_own
on public.club_messages for delete to authenticated
using (sender_id=(select auth.uid()));

drop policy if exists weekly_tournaments_read on public.weekly_tournaments;
create policy weekly_tournaments_read on public.weekly_tournaments for select to authenticated using(true);
drop policy if exists weekly_tournament_entries_read on public.weekly_tournament_entries;
create policy weekly_tournament_entries_read on public.weekly_tournament_entries for select to authenticated using(true);
drop policy if exists weekly_tournament_rewards_read_own on public.weekly_tournament_reward_claims;
create policy weekly_tournament_rewards_read_own
on public.weekly_tournament_reward_claims for select to authenticated
using(user_id=(select auth.uid()));

create or replace function public.create_club_v1(p_name text,p_tag text,p_description text default '')
returns uuid
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_name text:=btrim(coalesce(p_name,''));
  v_tag text:=upper(btrim(coalesce(p_tag,'')));
  v_description text:=btrim(coalesce(p_description,''));
  v_club uuid;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  if char_length(v_name) not between 3 and 24 then raise exception 'invalid_club_name'; end if;
  if char_length(v_tag) not between 2 and 6 or v_tag !~ '^[A-Z0-9ÇĞİÖŞÜ]+$' then raise exception 'invalid_club_tag'; end if;
  if char_length(v_description)>180 then raise exception 'description_too_long'; end if;
  if exists(select 1 from public.club_members where user_id=v_uid) then raise exception 'already_in_club'; end if;

  insert into public.clubs(name,tag,description,owner_id)
  values(v_name,v_tag,v_description,v_uid)
  returning id into v_club;

  insert into public.club_members(club_id,user_id,role)
  values(v_club,v_uid,'owner');

  return v_club;
exception when unique_violation then
  raise exception 'club_name_or_tag_taken';
end $$;

create or replace function public.join_club_v1(p_club_id uuid)
returns uuid
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_max int;
  v_count int;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  if exists(select 1 from public.club_members where user_id=v_uid) then raise exception 'already_in_club'; end if;

  select max_members into v_max from public.clubs where id=p_club_id for update;
  if v_max is null then raise exception 'club_not_found'; end if;

  select count(*)::int into v_count from public.club_members where club_id=p_club_id;
  if v_count>=v_max then raise exception 'club_full'; end if;

  insert into public.club_members(club_id,user_id,role)
  values(p_club_id,v_uid,'member');
  return p_club_id;
end $$;

create or replace function public.leave_club_v1()
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_club uuid;
  v_role text;
  v_count int;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  select club_id,role into v_club,v_role from public.club_members where user_id=v_uid;
  if v_club is null then raise exception 'not_in_club'; end if;

  select count(*)::int into v_count from public.club_members where club_id=v_club;
  if v_role='owner' and v_count>1 then raise exception 'transfer_owner_before_leaving'; end if;

  if v_role='owner' then
    delete from public.clubs where id=v_club;
  else
    delete from public.club_members where club_id=v_club and user_id=v_uid;
  end if;
end $$;

create or replace function public.transfer_club_owner_v1(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_club uuid;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  select club_id into v_club from public.club_members where user_id=v_uid and role='owner';
  if v_club is null then raise exception 'owner_required'; end if;
  if p_user_id=v_uid then return; end if;
  if not exists(select 1 from public.club_members where club_id=v_club and user_id=p_user_id) then
    raise exception 'target_not_member';
  end if;

  update public.club_members set role='member' where club_id=v_club and user_id=v_uid;
  update public.club_members set role='owner' where club_id=v_club and user_id=p_user_id;
  update public.clubs set owner_id=p_user_id,updated_at=now() where id=v_club;
end $$;

create or replace function public.get_club_directory_v1(p_limit integer default 30)
returns table(
  club_id uuid,name text,tag text,description text,member_count integer,max_members integer,
  weekly_points bigint,owner_name text
)
language sql
stable
security definer
set search_path=public,pg_temp
as $$
with week_boundary as (
  select (date_trunc('week', timezone('Europe/Istanbul',now())) at time zone 'Europe/Istanbul') as week_start
),
member_counts as (
  select club_id,count(*)::int member_count from public.club_members group by club_id
),
points as (
  select e.club_id,sum(e.points)::bigint weekly_points
  from public.club_point_events e, week_boundary w
  where e.created_at>=w.week_start
  group by e.club_id
)
select c.id,c.name,c.tag,c.description,coalesce(mc.member_count,0),c.max_members,
       coalesce(p.weekly_points,0),o.display_name
from public.clubs c
join public.profiles o on o.id=c.owner_id
left join member_counts mc on mc.club_id=c.id
left join points p on p.club_id=c.id
order by coalesce(p.weekly_points,0) desc,coalesce(mc.member_count,0) desc,lower(c.name)
limit greatest(1,least(coalesce(p_limit,30),100))
$$;

create or replace function public.get_my_club_v1()
returns table(
  club_id uuid,name text,tag text,description text,role text,member_count integer,
  max_members integer,weekly_points bigint,weekly_rank bigint
)
language sql
stable
security definer
set search_path=public,pg_temp
as $$
with me as (
  select cm.club_id,cm.role from public.club_members cm where cm.user_id=auth.uid()
),
week_boundary as (
  select (date_trunc('week', timezone('Europe/Istanbul',now())) at time zone 'Europe/Istanbul') as week_start
),
scores as (
  select c.id as club_id,
         coalesce(sum(e.points) filter(where e.created_at>=w.week_start),0)::bigint as pts
  from public.clubs c
  cross join week_boundary w
  left join public.club_point_events e on e.club_id=c.id
  group by c.id
),
ranked as (
  select club_id,pts,dense_rank() over(order by pts desc,club_id)::bigint as rnk from scores
)
select c.id,c.name,c.tag,c.description,m.role,
       (select count(*)::int from public.club_members x where x.club_id=c.id),
       c.max_members,r.pts,r.rnk
from me m
join public.clubs c on c.id=m.club_id
join ranked r on r.club_id=c.id
$$;

create or replace function public.get_club_members_v1(p_club_id uuid)
returns table(
  user_id uuid,display_name text,role text,rating integer,league_name text,
  weekly_points bigint,joined_at timestamptz
)
language sql
stable
security definer
set search_path=public,pg_temp
as $$
with week_boundary as (
  select (date_trunc('week', timezone('Europe/Istanbul',now())) at time zone 'Europe/Istanbul') as week_start
),
points as (
  select e.user_id,sum(e.points)::bigint pts
  from public.club_point_events e,week_boundary w
  where e.club_id=p_club_id and e.created_at>=w.week_start
  group by e.user_id
)
select cm.user_id,p.display_name,cm.role,p.rating,public.league_for_rating_v1(p.rating),
       coalesce(pt.pts,0),cm.joined_at
from public.club_members cm
join public.profiles p on p.id=cm.user_id
left join points pt on pt.user_id=cm.user_id
where cm.club_id=p_club_id
order by case cm.role when 'owner' then 0 when 'moderator' then 1 else 2 end,
         coalesce(pt.pts,0) desc,p.rating desc,lower(p.display_name)
$$;

create or replace function public.ensure_weekly_tournament_v1()
returns uuid
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_local_now timestamp:=timezone('Europe/Istanbul',now());
  v_week_start date:=date_trunc('week',v_local_now)::date;
  v_starts timestamptz:=(date_trunc('week',v_local_now) at time zone 'Europe/Istanbul');
  v_ends timestamptz:=((date_trunc('week',v_local_now)+interval '7 days') at time zone 'Europe/Istanbul');
  v_id uuid;
begin
  insert into public.weekly_tournaments(week_start,name,starts_at,ends_at)
  values(v_week_start,'Haftalık Kelime Kupası',v_starts,v_ends)
  on conflict(week_start) do update set name=excluded.name
  returning id into v_id;
  return v_id;
end $$;

create or replace function public.join_weekly_tournament_v1()
returns uuid
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_tid uuid;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  v_tid:=public.ensure_weekly_tournament_v1();
  insert into public.weekly_tournament_entries(tournament_id,user_id)
  values(v_tid,v_uid)
  on conflict(tournament_id,user_id) do nothing;
  return v_tid;
end $$;

create or replace function public.get_weekly_tournament_v1()
returns table(
  tournament_id uuid,name text,week_start date,starts_at timestamptz,ends_at timestamptz,
  joined boolean,my_points bigint,my_wins bigint,my_losses bigint,my_rank bigint,player_count bigint
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_tid uuid;
begin
  if auth.uid() is null then raise exception 'unauthorized'; end if;
  v_tid:=public.ensure_weekly_tournament_v1();

  return query
  with score as (
    select e.user_id,coalesce(sum(m.points),0)::bigint pts,
           count(*) filter(where m.won)::bigint wins,
           count(*) filter(where not m.won)::bigint losses
    from public.weekly_tournament_entries e
    left join public.weekly_tournament_match_events m
      on m.tournament_id=e.tournament_id and m.user_id=e.user_id
    where e.tournament_id=v_tid
    group by e.user_id
  ),
  ranked as (
    select s.*,dense_rank() over(order by s.pts desc,s.wins desc,s.user_id)::bigint rnk from score s
  )
  select t.id,t.name,t.week_start,t.starts_at,t.ends_at,
         exists(select 1 from public.weekly_tournament_entries e where e.tournament_id=t.id and e.user_id=auth.uid()),
         coalesce((select r.pts from ranked r where r.user_id=auth.uid()),0)::bigint,
         coalesce((select r.wins from ranked r where r.user_id=auth.uid()),0)::bigint,
         coalesce((select r.losses from ranked r where r.user_id=auth.uid()),0)::bigint,
         coalesce((select r.rnk from ranked r where r.user_id=auth.uid()),0)::bigint,
         (select count(*)::bigint from public.weekly_tournament_entries e where e.tournament_id=t.id)
  from public.weekly_tournaments t
  where t.id=v_tid;
end $$;

create or replace function public.get_weekly_tournament_leaderboard_v1(p_limit integer default 50)
returns table(
  user_id uuid,display_name text,rating integer,league_name text,points bigint,wins bigint,losses bigint,rank bigint
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_tid uuid;
begin
  if auth.uid() is null then raise exception 'unauthorized'; end if;
  v_tid:=public.ensure_weekly_tournament_v1();

  return query
  with score as (
    select e.user_id,coalesce(sum(m.points),0)::bigint pts,
           count(*) filter(where m.won)::bigint wins,
           count(*) filter(where not m.won)::bigint losses
    from public.weekly_tournament_entries e
    left join public.weekly_tournament_match_events m
      on m.tournament_id=e.tournament_id and m.user_id=e.user_id
    where e.tournament_id=v_tid
    group by e.user_id
  ),
  ranked as (
    select s.*,dense_rank() over(order by s.pts desc,s.wins desc,s.user_id)::bigint rnk from score s
  )
  select p.id,p.display_name,p.rating,public.league_for_rating_v1(p.rating),
         r.pts,r.wins,r.losses,r.rnk
  from ranked r
  join public.profiles p on p.id=r.user_id
  order by r.rnk,p.rating desc,lower(p.display_name)
  limit greatest(1,least(coalesce(p_limit,50),100));
end $$;

create or replace function public.claim_previous_weekly_tournament_reward_v1()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_tid uuid;
  v_rank int;
  v_reward int;
  v_balance int;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;

  select t.id into v_tid
  from public.weekly_tournaments t
  where t.ends_at<=now()
    and exists(select 1 from public.weekly_tournament_entries e where e.tournament_id=t.id and e.user_id=v_uid)
  order by t.ends_at desc
  limit 1;

  if v_tid is null then raise exception 'no_completed_tournament'; end if;
  if exists(select 1 from public.weekly_tournament_reward_claims c where c.tournament_id=v_tid and c.user_id=v_uid) then
    raise exception 'reward_already_claimed';
  end if;

  with score as (
    select e.user_id,coalesce(sum(m.points),0)::bigint pts,count(*) filter(where m.won)::bigint wins
    from public.weekly_tournament_entries e
    left join public.weekly_tournament_match_events m
      on m.tournament_id=e.tournament_id and m.user_id=e.user_id
    where e.tournament_id=v_tid
    group by e.user_id
  ),
  ranked as (
    select s.user_id,dense_rank() over(order by s.pts desc,s.wins desc,s.user_id)::int rnk from score s
  )
  select rnk into v_rank from ranked where user_id=v_uid;

  v_reward:=case
    when v_rank=1 then 1000
    when v_rank=2 then 600
    when v_rank=3 then 400
    when v_rank between 4 and 10 then 150
    else 50
  end;

  insert into public.weekly_tournament_reward_claims(tournament_id,user_id,final_rank,reward_coins)
  values(v_tid,v_uid,v_rank,v_reward);

  update public.profiles set diamonds=coalesce(diamonds,0)+v_reward
  where id=v_uid returning diamonds into v_balance;

  insert into public.diamond_ledger(user_id,delta,reason)
  values(v_uid,v_reward,'weekly_tournament_reward');

  return jsonb_build_object('success',true,'rank',v_rank,'reward_coins',v_reward,'balance',v_balance);
end $$;

create or replace function public.award_competition_points_v1()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_tid uuid;
  v_finished timestamptz:=coalesce(new.finished_at,now());
begin
  if not (new.stats_applied and not old.stats_applied and new.status='finished') then return new; end if;
  if coalesce(new.is_bot,false) then return new; end if;

  insert into public.club_point_events(club_id,user_id,room_id,points,created_at)
  select cm.club_id,new.host_id,new.id,case when new.winner_id=new.host_id then 10 else 3 end,v_finished
  from public.club_members cm where cm.user_id=new.host_id
  on conflict(room_id,user_id) do nothing;

  if new.guest_id is not null then
    insert into public.club_point_events(club_id,user_id,room_id,points,created_at)
    select cm.club_id,new.guest_id,new.id,case when new.winner_id=new.guest_id then 10 else 3 end,v_finished
    from public.club_members cm where cm.user_id=new.guest_id
    on conflict(room_id,user_id) do nothing;
  end if;

  select t.id into v_tid
  from public.weekly_tournaments t
  where v_finished>=t.starts_at and v_finished<t.ends_at
  order by t.starts_at desc
  limit 1;

  if v_tid is not null then
    insert into public.weekly_tournament_match_events(tournament_id,user_id,room_id,points,won,created_at)
    select v_tid,new.host_id,new.id,case when new.winner_id=new.host_id then 3 else 1 end,new.winner_id=new.host_id,v_finished
    where exists(
      select 1 from public.weekly_tournament_entries e
      where e.tournament_id=v_tid and e.user_id=new.host_id and e.joined_at<=v_finished
    )
    on conflict(tournament_id,room_id,user_id) do nothing;

    if new.guest_id is not null then
      insert into public.weekly_tournament_match_events(tournament_id,user_id,room_id,points,won,created_at)
      select v_tid,new.guest_id,new.id,case when new.winner_id=new.guest_id then 3 else 1 end,new.winner_id=new.guest_id,v_finished
      where exists(
        select 1 from public.weekly_tournament_entries e
        where e.tournament_id=v_tid and e.user_id=new.guest_id and e.joined_at<=v_finished
      )
      on conflict(tournament_id,room_id,user_id) do nothing;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists trg_award_competition_points_v1 on public.game_rooms;
create trigger trg_award_competition_points_v1
after update of stats_applied on public.game_rooms
for each row
when (new.stats_applied=true and old.stats_applied=false)
execute function public.award_competition_points_v1();

revoke all on function public.create_club_v1(text,text,text) from public,anon;
revoke all on function public.join_club_v1(uuid) from public,anon;
revoke all on function public.leave_club_v1() from public,anon;
revoke all on function public.transfer_club_owner_v1(uuid) from public,anon;
revoke all on function public.get_club_directory_v1(integer) from public,anon;
revoke all on function public.get_my_club_v1() from public,anon;
revoke all on function public.get_club_members_v1(uuid) from public,anon;
revoke all on function public.ensure_weekly_tournament_v1() from public,anon;
revoke all on function public.join_weekly_tournament_v1() from public,anon;
revoke all on function public.get_weekly_tournament_v1() from public,anon;
revoke all on function public.get_weekly_tournament_leaderboard_v1(integer) from public,anon;
revoke all on function public.claim_previous_weekly_tournament_reward_v1() from public,anon;

grant execute on function public.create_club_v1(text,text,text) to authenticated;
grant execute on function public.join_club_v1(uuid) to authenticated;
grant execute on function public.leave_club_v1() to authenticated;
grant execute on function public.transfer_club_owner_v1(uuid) to authenticated;
grant execute on function public.get_club_directory_v1(integer) to authenticated;
grant execute on function public.get_my_club_v1() to authenticated;
grant execute on function public.get_club_members_v1(uuid) to authenticated;
revoke execute on function public.ensure_weekly_tournament_v1() from authenticated;
revoke execute on function public.award_competition_points_v1() from public,anon,authenticated;
revoke execute on function public.league_for_rating_v1(integer) from public,anon;
grant execute on function public.league_for_rating_v1(integer) to authenticated;
grant execute on function public.join_weekly_tournament_v1() to authenticated;
grant execute on function public.get_weekly_tournament_v1() to authenticated;
grant execute on function public.get_weekly_tournament_leaderboard_v1(integer) to authenticated;
grant execute on function public.claim_previous_weekly_tournament_reward_v1() to authenticated;
