-- Word Arena v1: simultaneous 60-second word duel.
-- Same letters for both players, unique words score 2x at finalization.
-- Competitive entry remains free and all rewards are earned.

create or replace function public.arena_word_fits_letters_v1(p_word text,p_letters text)
returns boolean
language sql
immutable
set search_path=public,pg_temp
as $$
  with wc as (
    select ch,count(*)::int n
    from regexp_split_to_table(coalesce(p_word,''),'') ch
    where ch<>''
    group by ch
  ),
  lc as (
    select ch,count(*)::int n
    from regexp_split_to_table(coalesce(p_letters,''),'') ch
    where ch<>''
    group by ch
  )
  select coalesce(bool_and(wc.n<=coalesce(lc.n,0)),true)
  from wc left join lc using(ch)
$;

revoke all on function public.arena_word_fits_letters_v1(text,text) from public,anon,authenticated;

create table if not exists public.word_arena_rooms (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  guest_id uuid not null references public.profiles(id) on delete cascade,
  language text not null check(language in ('tr','en')),
  letters text not null,
  status text not null default 'playing' check(status in ('playing','finished','cancelled')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  host_score integer not null default 0 check(host_score>=0),
  guest_score integer not null default 0 check(guest_score>=0),
  winner_id uuid references public.profiles(id) on delete set null,
  result_applied boolean not null default false,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  check(host_id<>guest_id),
  check(ends_at>starts_at)
);

create index if not exists word_arena_rooms_host_created_idx on public.word_arena_rooms(host_id,created_at desc);
create index if not exists word_arena_rooms_guest_created_idx on public.word_arena_rooms(guest_id,created_at desc);
create index if not exists word_arena_rooms_status_end_idx on public.word_arena_rooms(status,ends_at);
create index if not exists word_arena_rooms_winner_idx
  on public.word_arena_rooms(winner_id)
  where winner_id is not null;

create table if not exists public.word_arena_queue (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  language text not null check(language in ('tr','en')),
  status text not null default 'waiting' check(status in ('waiting','matched','cancelled')),
  room_id uuid references public.word_arena_rooms(id) on delete set null,
  queued_at timestamptz not null default now(),
  heartbeat_at timestamptz not null default now()
);
create index if not exists word_arena_queue_waiting_idx
  on public.word_arena_queue(language,queued_at)
  where status='waiting';
create index if not exists word_arena_queue_room_idx
  on public.word_arena_queue(room_id)
  where room_id is not null;

create table if not exists public.word_arena_words (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.word_arena_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  word text not null,
  normalized_word text not null,
  base_points integer not null check(base_points between 1 and 100),
  combo integer not null default 1 check(combo between 1 and 99),
  created_at timestamptz not null default now(),
  unique(room_id,user_id,normalized_word)
);
create index if not exists word_arena_words_room_created_idx
  on public.word_arena_words(room_id,created_at);
create index if not exists word_arena_words_room_user_idx
  on public.word_arena_words(room_id,user_id);
create index if not exists word_arena_words_user_idx
  on public.word_arena_words(user_id);

alter table public.word_arena_rooms enable row level security;
alter table public.word_arena_queue enable row level security;
alter table public.word_arena_words enable row level security;

revoke all on public.word_arena_rooms from anon,authenticated;
revoke all on public.word_arena_queue from anon,authenticated;
revoke all on public.word_arena_words from anon,authenticated;

alter table public.club_point_events
  add column if not exists arena_room_id uuid references public.word_arena_rooms(id) on delete cascade;
alter table public.club_point_events alter column room_id drop not null;
alter table public.club_point_events
  drop constraint if exists club_point_events_source_check;
alter table public.club_point_events
  add constraint club_point_events_source_check
  check (num_nonnulls(room_id,arena_room_id)=1);
create unique index if not exists club_point_events_arena_user_uq
  on public.club_point_events(arena_room_id,user_id)
  where arena_room_id is not null;

alter table public.weekly_tournament_match_events
  add column if not exists arena_room_id uuid references public.word_arena_rooms(id) on delete cascade;
alter table public.weekly_tournament_match_events alter column room_id drop not null;
alter table public.weekly_tournament_match_events
  drop constraint if exists weekly_tournament_match_events_source_check;
alter table public.weekly_tournament_match_events
  add constraint weekly_tournament_match_events_source_check
  check (num_nonnulls(room_id,arena_room_id)=1);
create unique index if not exists weekly_tournament_arena_user_uq
  on public.weekly_tournament_match_events(tournament_id,arena_room_id,user_id)
  where arena_room_id is not null;
create index if not exists weekly_tournament_match_events_arena_idx
  on public.weekly_tournament_match_events(arena_room_id)
  where arena_room_id is not null;

create or replace function public.word_arena_letter_set_v1(p_language text)
returns text
language plpgsql
volatile
set search_path=public,pg_temp
as $$
declare
  v_sets text[];
  v_idx int;
begin
  if lower(coalesce(p_language,'tr'))='en' then
    v_sets:=array[
      'aeimnorst','aelnrstio','aelrstion','aerlnstic','aerstlinc','aeglnrstu'
    ];
  else
    v_sets:=array[
      'aelrmtskin','aerltmison','aeilmnorst','aelrktsuin',
      'aeiklnrst','aerlnmikt','aeılnrstok','aegilnrstu'
    ];
  end if;
  v_idx:=1+floor(random()*array_length(v_sets,1))::int;
  return v_sets[v_idx];
end
$;

create or replace function public.finish_word_arena_internal_v1(p_room_id uuid)
returns public.word_arena_rooms
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  r public.word_arena_rooms;
  v_uid uuid:=auth.uid();
  v_host_score int:=0;
  v_guest_score int:=0;
  v_host_words int:=0;
  v_guest_words int:=0;
  v_winner uuid;
  v_host_reward int:=0;
  v_guest_reward int:=0;
  v_tid uuid;
  v_finished timestamptz;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;

  select * into r
  from public.word_arena_rooms
  where id=p_room_id
  for update;

  if r.id is null then raise exception 'arena_room_not_found'; end if;
  if v_uid not in (r.host_id,r.guest_id) then raise exception 'arena_not_participant'; end if;
  if r.status='finished' then return r; end if;
  if r.status<>'playing' then raise exception 'arena_not_active'; end if;
  if now()<r.ends_at then raise exception 'arena_not_finished_yet'; end if;

  select coalesce(sum(
    w.base_points +
    case when not exists(
      select 1 from public.word_arena_words o
      where o.room_id=w.room_id
        and o.user_id=r.guest_id
        and o.normalized_word=w.normalized_word
    ) then w.base_points else 0 end
  ),0)::int,
  count(*)::int
  into v_host_score,v_host_words
  from public.word_arena_words w
  where w.room_id=r.id and w.user_id=r.host_id;

  select coalesce(sum(
    w.base_points +
    case when not exists(
      select 1 from public.word_arena_words o
      where o.room_id=w.room_id
        and o.user_id=r.host_id
        and o.normalized_word=w.normalized_word
    ) then w.base_points else 0 end
  ),0)::int,
  count(*)::int
  into v_guest_score,v_guest_words
  from public.word_arena_words w
  where w.room_id=r.id and w.user_id=r.guest_id;

  v_winner:=case
    when v_host_score>v_guest_score then r.host_id
    when v_guest_score>v_host_score then r.guest_id
    else null
  end;

  if not r.result_applied then
    update public.profiles
    set total_matches=total_matches+1,
        wins=wins+case when v_winner=id then 1 else 0 end,
        losses=losses+case when v_winner is not null and v_winner<>id then 1 else 0 end,
        valid_words=valid_words+case when id=r.host_id then v_host_words else v_guest_words end,
        rating=greatest(
          100,
          rating+case
            when v_winner is null then 0
            when v_winner=id then 18
            else -12
          end
        ),
        presence_status='online',
        last_seen_at=now()
    where id in (r.host_id,r.guest_id);

    v_host_reward:=case
      when v_winner is null then 7
      when v_winner=r.host_id then 12
      else 5
    end;
    v_guest_reward:=case
      when v_winner is null then 7
      when v_winner=r.guest_id then 12
      else 5
    end;

    update public.profiles
    set diamonds=diamonds+case when id=r.host_id then v_host_reward else v_guest_reward end
    where id in (r.host_id,r.guest_id);

    insert into public.diamond_ledger(user_id,delta,reason,item_id)
    values
      (r.host_id,v_host_reward,'word_arena_match:'||r.id::text,null),
      (r.guest_id,v_guest_reward,'word_arena_match:'||r.id::text,null);

    v_finished:=coalesce(r.ends_at,now());

    insert into public.club_point_events(club_id,user_id,room_id,arena_room_id,points,created_at)
    select cm.club_id,r.host_id,null,r.id,
           case when v_winner is null then 5 when v_winner=r.host_id then 10 else 3 end,
           v_finished
    from public.club_members cm
    where cm.user_id=r.host_id
    on conflict do nothing;

    insert into public.club_point_events(club_id,user_id,room_id,arena_room_id,points,created_at)
    select cm.club_id,r.guest_id,null,r.id,
           case when v_winner is null then 5 when v_winner=r.guest_id then 10 else 3 end,
           v_finished
    from public.club_members cm
    where cm.user_id=r.guest_id
    on conflict do nothing;

    select t.id into v_tid
    from public.weekly_tournaments t
    where v_finished>=t.starts_at and v_finished<t.ends_at
    order by t.starts_at desc
    limit 1;

    if v_tid is not null then
      insert into public.weekly_tournament_match_events(
        tournament_id,user_id,room_id,arena_room_id,points,won,created_at
      )
      select v_tid,r.host_id,null,r.id,
             case when v_winner is null then 2 when v_winner=r.host_id then 3 else 1 end,
             v_winner=r.host_id,
             v_finished
      where exists(
        select 1 from public.weekly_tournament_entries e
        where e.tournament_id=v_tid
          and e.user_id=r.host_id
          and e.joined_at<=r.starts_at
      )
      on conflict do nothing;

      insert into public.weekly_tournament_match_events(
        tournament_id,user_id,room_id,arena_room_id,points,won,created_at
      )
      select v_tid,r.guest_id,null,r.id,
             case when v_winner is null then 2 when v_winner=r.guest_id then 3 else 1 end,
             v_winner=r.guest_id,
             v_finished
      where exists(
        select 1 from public.weekly_tournament_entries e
        where e.tournament_id=v_tid
          and e.user_id=r.guest_id
          and e.joined_at<=r.starts_at
      )
      on conflict do nothing;
    end if;
  end if;

  update public.word_arena_rooms
  set status='finished',
      host_score=v_host_score,
      guest_score=v_guest_score,
      winner_id=v_winner,
      result_applied=true,
      finished_at=now()
  where id=r.id
  returning * into r;

  update public.word_arena_queue
  set status='cancelled',heartbeat_at=now()
  where user_id in (r.host_id,r.guest_id);

  return r;
end
$;

create or replace function public.join_word_arena_v1(p_language text default 'tr')
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_lang text:=case when lower(trim(coalesce(p_language,'tr')))='en' then 'en' else 'tr' end;
  v_opponent uuid;
  v_room public.word_arena_rooms;
  v_existing public.word_arena_rooms;
  v_my_rating int;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;

  perform pg_advisory_xact_lock(88220011);

  select * into v_existing
  from public.word_arena_rooms
  where status='playing'
    and (host_id=v_uid or guest_id=v_uid)
  order by created_at desc
  limit 1;

  if v_existing.id is not null then
    if now()>=v_existing.ends_at then
      v_existing:=public.finish_word_arena_internal_v1(v_existing.id);
    else
      return jsonb_build_object('status','matched','room_id',v_existing.id);
    end if;
  end if;

  if exists(
    select 1 from public.game_rooms
    where status in ('playing','quiz','final','sudden_death')
      and (host_id=v_uid or guest_id=v_uid)
  ) then
    raise exception 'player_already_in_game';
  end if;

  update public.word_arena_queue
  set status='cancelled'
  where status='waiting'
    and heartbeat_at<now()-interval '90 seconds';

  select coalesce(rating,1000) into v_my_rating
  from public.profiles where id=v_uid;

  select q.user_id into v_opponent
  from public.word_arena_queue q
  join public.profiles p on p.id=q.user_id
  where q.status='waiting'
    and q.language=v_lang
    and q.user_id<>v_uid
    and q.heartbeat_at>=now()-interval '90 seconds'
    and not exists(
      select 1 from public.user_blocks b
      where (b.blocker_id=v_uid and b.blocked_id=q.user_id)
         or (b.blocker_id=q.user_id and b.blocked_id=v_uid)
    )
    and not exists(
      select 1 from public.word_arena_rooms ar
      where ar.status='playing'
        and (ar.host_id=q.user_id or ar.guest_id=q.user_id)
    )
    and not exists(
      select 1 from public.game_rooms gr
      where gr.status in ('playing','quiz','final','sudden_death')
        and (gr.host_id=q.user_id or gr.guest_id=q.user_id)
    )
  order by abs(coalesce(p.rating,1000)-v_my_rating),q.queued_at
  for update of q skip locked
  limit 1;

  if v_opponent is null then
    insert into public.word_arena_queue(user_id,language,status,room_id,queued_at,heartbeat_at)
    values(v_uid,v_lang,'waiting',null,now(),now())
    on conflict(user_id) do update set
      language=excluded.language,
      status='waiting',
      room_id=null,
      queued_at=case
        when public.word_arena_queue.status='waiting'
         and public.word_arena_queue.language=excluded.language
        then public.word_arena_queue.queued_at
        else now()
      end,
      heartbeat_at=now();

    update public.profiles set presence_status='online',last_seen_at=now() where id=v_uid;
    return jsonb_build_object('status','waiting');
  end if;

  insert into public.word_arena_rooms(
    host_id,guest_id,language,letters,status,starts_at,ends_at
  )
  values(
    v_opponent,
    v_uid,
    v_lang,
    public.word_arena_letter_set_v1(v_lang),
    'playing',
    now()+interval '3 seconds',
    now()+interval '63 seconds'
  )
  returning * into v_room;

  update public.word_arena_queue
  set status='matched',room_id=v_room.id,heartbeat_at=now()
  where user_id=v_opponent;

  insert into public.word_arena_queue(user_id,language,status,room_id,queued_at,heartbeat_at)
  values(v_uid,v_lang,'matched',v_room.id,now(),now())
  on conflict(user_id) do update set
    language=excluded.language,
    status='matched',
    room_id=excluded.room_id,
    queued_at=now(),
    heartbeat_at=now();

  update public.profiles
  set presence_status='in_game',last_seen_at=now()
  where id in (v_uid,v_opponent);

  return jsonb_build_object('status','matched','room_id',v_room.id);
end
$;

create or replace function public.poll_word_arena_v1()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  q public.word_arena_queue;
  r public.word_arena_rooms;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;

  select * into q from public.word_arena_queue where user_id=v_uid;
  if q.user_id is null then return jsonb_build_object('status','idle'); end if;

  if q.status='waiting' then
    update public.word_arena_queue set heartbeat_at=now() where user_id=v_uid;
    return jsonb_build_object('status','waiting');
  end if;

  if q.room_id is not null then
    select * into r from public.word_arena_rooms where id=q.room_id;
    if r.id is not null and r.status='playing' and now()>=r.ends_at then
      r:=public.finish_word_arena_internal_v1(r.id);
    end if;
    return jsonb_build_object(
      'status',case when r.status='finished' then 'finished' else 'matched' end,
      'room_id',q.room_id
    );
  end if;

  return jsonb_build_object('status',q.status);
end
$;

create or replace function public.cancel_word_arena_v1()
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_uid uuid:=auth.uid();
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  update public.word_arena_queue
  set status='cancelled',room_id=null,heartbeat_at=now()
  where user_id=v_uid and status='waiting';
  update public.profiles set presence_status='online',last_seen_at=now() where id=v_uid;
end
$;

create or replace function public.get_word_arena_room_v1(p_room_id uuid)
returns public.word_arena_rooms
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  r public.word_arena_rooms;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  select * into r from public.word_arena_rooms where id=p_room_id;
  if r.id is null then raise exception 'arena_room_not_found'; end if;
  if v_uid not in (r.host_id,r.guest_id) then raise exception 'arena_not_participant'; end if;
  if r.status='playing' and now()>=r.ends_at then
    r:=public.finish_word_arena_internal_v1(r.id);
  end if;
  return r;
end
$;

create or replace function public.get_word_arena_words_v1(p_room_id uuid)
returns table(
  id bigint,
  user_id uuid,
  word text,
  normalized_word text,
  base_points integer,
  combo integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  r public.word_arena_rooms;
begin
  if v_uid is null then raise exception 'unauthorized'; end if;
  select ar.* into r
  from public.word_arena_rooms ar
  where ar.id=p_room_id;
  if r.id is null then raise exception 'arena_room_not_found'; end if;
  if v_uid not in (r.host_id,r.guest_id) then raise exception 'arena_not_participant'; end if;

  return query
  select w.id,w.user_id,w.word,w.normalized_word,w.base_points,w.combo,w.created_at
  from public.word_arena_words w
  where w.room_id=p_room_id
    and (r.status='finished' or w.user_id=v_uid)
  order by w.created_at,w.id;
end
$;

create or replace function public.submit_word_arena_v1(p_room_id uuid,p_word text)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  r public.word_arena_rooms;
  v_norm text;
  v_len int;
  v_combo int:=1;
  v_prev public.word_arena_words;
  v_points int;
  v_score int;
  v_word text:=trim(coalesce(p_word,''));
begin
  if v_uid is null then raise exception 'unauthorized'; end if;

  select * into r
  from public.word_arena_rooms
  where id=p_room_id
  for update;

  if r.id is null then raise exception 'arena_room_not_found'; end if;
  if v_uid not in (r.host_id,r.guest_id) then raise exception 'arena_not_participant'; end if;
  if r.status<>'playing' then return jsonb_build_object('accepted',false,'status',r.status); end if;

  if now()>=r.ends_at then
    r:=public.finish_word_arena_internal_v1(r.id);
    return jsonb_build_object('accepted',false,'status','finished');
  end if;

  if now()<r.starts_at then raise exception 'arena_not_started'; end if;

  v_norm:=public.normalize_game_word(r.language,v_word);
  v_len:=char_length(v_norm);

  if v_len<3 or v_len>10 then raise exception 'arena_word_length'; end if;
  if not public.arena_word_fits_letters_v1(v_norm,r.letters) then raise exception 'arena_letters_mismatch'; end if;

  if not exists(
    select 1 from public.dictionary_words d
    where d.language=r.language
      and d.active
      and d.normalized_word=v_norm
  ) then
    raise exception 'arena_invalid_word';
  end if;

  if exists(
    select 1 from public.word_arena_words w
    where w.room_id=r.id and w.user_id=v_uid and w.normalized_word=v_norm
  ) then
    raise exception 'arena_duplicate_word';
  end if;

  select * into v_prev
  from public.word_arena_words
  where room_id=r.id and user_id=v_uid
  order by created_at desc,id desc
  limit 1;

  if v_prev.id is not null and now()-v_prev.created_at<=interval '8 seconds' then
    v_combo:=least(v_prev.combo+1,99);
  end if;

  v_points:=
    v_len
    +greatest(0,v_len-4)*2
    +least(greatest(v_combo-1,0),4);

  insert into public.word_arena_words(
    room_id,user_id,word,normalized_word,base_points,combo
  )
  values(r.id,v_uid,v_word,v_norm,v_points,v_combo);

  select coalesce(sum(base_points),0)::int into v_score
  from public.word_arena_words
  where room_id=r.id and user_id=v_uid;

  update public.word_arena_rooms
  set host_score=case when v_uid=host_id then v_score else host_score end,
      guest_score=case when v_uid=guest_id then v_score else guest_score end
  where id=r.id;

  return jsonb_build_object(
    'accepted',true,
    'status','playing',
    'word',v_word,
    'normalized_word',v_norm,
    'base_points',v_points,
    'combo',v_combo,
    'provisional_score',v_score
  );
end
$;

create or replace function public.prevent_sonharf_queue_during_word_arena_v1()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $$
begin
  if new.status='waiting' and exists(
    select 1 from public.word_arena_rooms r
    where r.status='playing'
      and (r.host_id=new.user_id or r.guest_id=new.user_id)
      and r.ends_at>now()
  ) then
    raise exception 'word_arena_match_active';
  end if;
  return new;
end
$;

drop trigger if exists trg_prevent_sonharf_queue_during_word_arena_v1 on public.matchmaking_queue;
create trigger trg_prevent_sonharf_queue_during_word_arena_v1
before insert or update of status on public.matchmaking_queue
for each row execute function public.prevent_sonharf_queue_during_word_arena_v1();

create or replace function public.prevent_game_room_during_word_arena_v1()
returns trigger
language plpgsql
set search_path=public,pg_temp
as $
begin
  if exists(
    select 1 from public.word_arena_rooms ar
    where ar.status='playing'
      and ar.ends_at>now()
      and (
        ar.host_id in (new.host_id,new.guest_id)
        or ar.guest_id in (new.host_id,new.guest_id)
      )
  ) then
    raise exception 'word_arena_match_active';
  end if;
  return new;
end
$;

drop trigger if exists trg_prevent_game_room_during_word_arena_v1 on public.game_rooms;
create trigger trg_prevent_game_room_during_word_arena_v1
before insert on public.game_rooms
for each row execute function public.prevent_game_room_during_word_arena_v1();

revoke all on function public.word_arena_letter_set_v1(text) from public,anon,authenticated;
revoke all on function public.finish_word_arena_internal_v1(uuid) from public,anon,authenticated;
revoke all on function public.prevent_sonharf_queue_during_word_arena_v1() from public,anon,authenticated;
revoke all on function public.prevent_game_room_during_word_arena_v1() from public,anon,authenticated;

revoke all on function public.join_word_arena_v1(text) from public,anon;
revoke all on function public.poll_word_arena_v1() from public,anon;
revoke all on function public.cancel_word_arena_v1() from public,anon;
revoke all on function public.get_word_arena_room_v1(uuid) from public,anon;
revoke all on function public.get_word_arena_words_v1(uuid) from public,anon;
revoke all on function public.submit_word_arena_v1(uuid,text) from public,anon;

grant execute on function public.join_word_arena_v1(text) to authenticated;
grant execute on function public.poll_word_arena_v1() to authenticated;
grant execute on function public.cancel_word_arena_v1() to authenticated;
grant execute on function public.get_word_arena_room_v1(uuid) to authenticated;
grant execute on function public.get_word_arena_words_v1(uuid) to authenticated;
grant execute on function public.submit_word_arena_v1(uuid,text) to authenticated;
