-- Word Siege v6: recover production drift and enforce canonical 15x15 server geometry.
-- This migration is intentionally forward-only and idempotent:
-- - fresh databases may already have the v4 15x15 helpers;
-- - drifted production databases may still have 9x9 helpers/validators.
-- Preserve the newer shared dictionary validator and v5 final-score semantics.

-- Serialize board/move conversion against live game writes.
lock table public.word_siege_games in share row exclusive mode;
lock table public.word_siege_moves in share row exclusive mode;

create or replace function private.word_siege_new_board_v1()
returns jsonb
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  select jsonb_agg(
    jsonb_build_object(
      'letter', null,
      'owner', 0,
      'bonus', case
        when i in (0,7,14,105,119,210,217,224) then '3K'
        when i in (20,24,76,80,84,88,136,140,144,148,200,204) then '3H'
        when i in (16,28,32,42,48,56,64,70,112,154,160,168,176,182,192,196,208) then '2K'
        when i in (3,11,36,38,45,52,59,92,96,98,102,108,116,122,126,128,132,165,172,179,186,188,213,221) then '2H'
        else null
      end,
      'bonus_used', false
    ) order by i
  )
  from generate_series(0, 224) i
$$;

-- Remap legacy 9x9 move coordinates into the centered 9x9 region of the 15x15 board.
update public.word_siege_moves m
set placed_tiles = (
  select coalesce(
    jsonb_agg(
      tile || jsonb_build_object(
        'index', ((((tile ->> 'index')::integer / 9) + 3) * 15)
                 + (((tile ->> 'index')::integer % 9) + 3)
      ) order by ordinality
    ),
    '[]'::jsonb
  )
  from jsonb_array_elements(m.placed_tiles) with ordinality as t(tile, ordinality)
)
where exists (
  select 1
  from public.word_siege_games g
  where g.id = m.game_id
    and jsonb_typeof(g.board) = 'array'
    and jsonb_array_length(g.board) = 81
);

-- Preserve legacy letters, ownership and used-bonus state while centering the old board.
update public.word_siege_games g
set board = (
  with fresh as (select private.word_siege_new_board_v1() as board)
  select jsonb_agg(
    case
      when (i / 15) between 3 and 11 and (i % 15) between 3 and 11 then
        (fresh.board -> i) || jsonb_build_object(
          'letter', g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'letter',
          'owner', coalesce(
            g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'owner',
            '0'::jsonb
          ),
          'bonus_used', coalesce(
            g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'bonus_used',
            'false'::jsonb
          )
        )
      else fresh.board -> i
    end
    order by i
  )
  from fresh, generate_series(0, 224) i
)
where jsonb_typeof(g.board) = 'array'
  and jsonb_array_length(g.board) = 81;

-- Remove any legacy 81-cell checks without depending on autogenerated constraint names.
do $constraints$
declare
  c record;
begin
  for c in
    select conname, pg_get_constraintdef(oid) as definition
    from pg_constraint
    where conrelid = 'public.word_siege_games'::regclass
      and contype = 'c'
  loop
    if c.definition like '%player_one_area%81%'
       or c.definition like '%player_two_area%81%'
       or c.definition like '%jsonb_array_length(board)%81%' then
      execute format('alter table public.word_siege_games drop constraint %I', c.conname);
    end if;
  end loop;
end
$constraints$;

alter table public.word_siege_games
  drop constraint if exists word_siege_games_player_one_area_v6_check;
alter table public.word_siege_games
  drop constraint if exists word_siege_games_player_two_area_v6_check;
alter table public.word_siege_games
  drop constraint if exists word_siege_games_board_v6_check;

alter table public.word_siege_games
  add constraint word_siege_games_player_one_area_v6_check
    check (player_one_area between 0 and 225),
  add constraint word_siege_games_player_two_area_v6_check
    check (player_two_area between 0 and 225),
  add constraint word_siege_games_board_v6_check
    check (jsonb_typeof(board) = 'array' and jsonb_array_length(board) = 225);

create or replace function private.word_siege_collect_cells_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_anchor integer,
  p_delta integer
)
returns integer[]
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_start integer := p_anchor;
  v_current integer;
  v_next integer;
  v_cells integer[] := array[]::integer[];
begin
  if p_delta not in (1, 15) or p_anchor not between 0 and 224 then
    return v_cells;
  end if;
  if private.word_siege_letter_at_v1(p_board, p_placements, p_rack, p_anchor) is null then
    return v_cells;
  end if;

  loop
    v_next := v_start - p_delta;
    exit when v_next < 0;
    exit when p_delta = 1 and (v_next / 15) <> (v_start / 15);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_next) is null;
    v_start := v_next;
  end loop;

  v_current := v_start;
  loop
    exit when v_current > 224;
    exit when p_delta = 1 and (v_current / 15) <> (v_start / 15);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_current) is null;
    v_cells := array_append(v_cells, v_current);
    v_next := v_current + p_delta;
    exit when v_next > 224;
    exit when p_delta = 1 and (v_next / 15) <> (v_current / 15);
    v_current := v_next;
  end loop;

  return v_cells;
end
$$;

create or replace function private.word_siege_area_delta_v1(
  p_before_board jsonb,
  p_after_board jsonb,
  p_owner integer
)
returns table(neutral_captured integer, opponent_captured integer, area_score integer)
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  with ownership as (
    select i,
      coalesce((p_before_board -> i ->> 'owner')::integer, 0) as before_owner,
      coalesce((p_after_board -> i ->> 'owner')::integer, 0) as after_owner
    from generate_series(0, 224) i
  ), counts as (
    select
      count(*) filter (where before_owner = 0 and after_owner = p_owner)::integer as neutral_count,
      count(*) filter (
        where before_owner not in (0, p_owner) and after_owner = p_owner
      )::integer as opponent_count
    from ownership
  )
  select neutral_count, opponent_count, (neutral_count + opponent_count) * 2
  from counts
$$;

-- Preserve all newer submit behavior and patch only its board-geometry contract.
do $submit_geometry$
declare
  v_def text;
  v_src text;
begin
  select pg_get_functiondef(
    'private.submit_word_siege_move_v1(uuid,jsonb,boolean)'::regprocedure
  ) into v_def;
  if v_def is null then
    raise exception 'word_siege_submit_function_missing';
  end if;

  v_def := replace(v_def, 'x not between 0 and 80', 'x not between 0 and 224');
  v_def := replace(v_def, 'x / 9 <> v_anchor / 9', 'x / 15 <> v_anchor / 15');
  v_def := replace(v_def, 'x % 9 <> v_anchor % 9', 'x % 15 <> v_anchor % 15');
  v_def := replace(v_def, 'case when p_horizontal then 1 else 9 end', 'case when p_horizontal then 1 else 15 end');
  v_def := replace(v_def, 'case when p_horizontal then 9 else 1 end', 'case when p_horizontal then 15 else 1 end');
  v_def := replace(v_def, '40 = any(v_indices)', '112 = any(v_indices)');
  execute v_def;

  select p.prosrc into v_src
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'private'
    and p.proname = 'submit_word_siege_move_v1'
    and p.oid = 'private.submit_word_siege_move_v1(uuid,jsonb,boolean)'::regprocedure;

  if v_src not like '%x not between 0 and 224%'
     or v_src not like '%x / 15 <> v_anchor / 15%'
     or v_src not like '%x % 15 <> v_anchor % 15%'
     or v_src not like '%112 = any(v_indices)%'
     or v_src like '%x not between 0 and 80%'
     or v_src like '%x / 9 <> v_anchor / 9%'
     or v_src like '%x % 9 <> v_anchor % 9%'
     or v_src like '%40 = any(v_indices)%' then
    raise exception 'word_siege_submit_geometry_patch_failed';
  end if;
end
$submit_geometry$;

-- The public submit wrapper calls this before the authoritative submit function,
-- so prevalidation must use exactly the same 15x15 geometry.
do $prevalidate_geometry$
declare
  v_def text;
  v_src text;
begin
  select pg_get_functiondef(
    'private.word_siege_prevalidate_move_v2(uuid,jsonb,boolean)'::regprocedure
  ) into v_def;
  if v_def is null then
    raise exception 'word_siege_prevalidate_function_missing';
  end if;

  v_def := replace(v_def, 'x not between 0 and 80', 'x not between 0 and 224');
  v_def := replace(v_def, 'x / 9 <> v_anchor / 9', 'x / 15 <> v_anchor / 15');
  v_def := replace(v_def, 'x % 9 <> v_anchor % 9', 'x % 15 <> v_anchor % 15');
  v_def := replace(v_def, 'case when p_horizontal then 1 else 9 end', 'case when p_horizontal then 1 else 15 end');
  v_def := replace(v_def, 'case when p_horizontal then 9 else 1 end', 'case when p_horizontal then 15 else 1 end');
  v_def := replace(v_def, '40 = any(v_indices)', '112 = any(v_indices)');
  execute v_def;

  select p.prosrc into v_src
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'private'
    and p.proname = 'word_siege_prevalidate_move_v2'
    and p.oid = 'private.word_siege_prevalidate_move_v2(uuid,jsonb,boolean)'::regprocedure;

  if v_src not like '%x not between 0 and 224%'
     or v_src not like '%x / 15 <> v_anchor / 15%'
     or v_src not like '%x % 15 <> v_anchor % 15%'
     or v_src not like '%112 = any(v_indices)%'
     or v_src like '%x not between 0 and 80%'
     or v_src like '%x / 9 <> v_anchor / 9%'
     or v_src like '%x % 9 <> v_anchor % 9%'
     or v_src like '%40 = any(v_indices)%' then
    raise exception 'word_siege_prevalidate_geometry_patch_failed';
  end if;
end
$prevalidate_geometry$;

-- Preview must match submit/prevalidate, including perpendicular scans and area preview range.
do $preview_geometry$
declare
  v_def text;
  v_src text;
begin
  select pg_get_functiondef(
    'private.word_siege_preview_move_v1(uuid,jsonb,boolean)'::regprocedure
  ) into v_def;
  if v_def is null then
    raise exception 'word_siege_preview_function_missing';
  end if;

  v_def := replace(v_def, 'case when p_horizontal then 1 else 9 end', 'case when p_horizontal then 1 else 15 end');
  v_def := replace(v_def, 'case when p_horizontal then 9 else 1 end', 'case when p_horizontal then 15 else 1 end');
  v_def := replace(v_def, 'generate_series(0,80)', 'generate_series(0,224)');
  v_def := replace(v_def, 'generate_series(0, 80)', 'generate_series(0, 224)');
  execute v_def;

  select p.prosrc into v_src
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'private'
    and p.proname = 'word_siege_preview_move_v1'
    and p.oid = 'private.word_siege_preview_move_v1(uuid,jsonb,boolean)'::regprocedure;

  if v_src not like '%case when p_horizontal then 1 else 15 end%'
     or v_src not like '%case when p_horizontal then 15 else 1 end%'
     or (v_src not like '%generate_series(0,224)%'
         and v_src not like '%generate_series(0, 224)%')
     or v_src like '%case when p_horizontal then 1 else 9 end%'
     or v_src like '%case when p_horizontal then 9 else 1 end%'
     or v_src like '%generate_series(0,80)%'
     or v_src like '%generate_series(0, 80)%' then
    raise exception 'word_siege_preview_geometry_patch_failed';
  end if;
end
$preview_geometry$;

-- Private engine functions stay inaccessible from exposed client roles.
revoke all on function private.word_siege_new_board_v1() from public, anon, authenticated;
revoke all on function private.word_siege_collect_cells_v1(jsonb, jsonb, text, integer, integer) from public, anon, authenticated;
revoke all on function private.word_siege_area_delta_v1(jsonb, jsonb, integer) from public, anon, authenticated;
revoke all on function private.submit_word_siege_move_v1(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function private.word_siege_prevalidate_move_v2(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function private.word_siege_preview_move_v1(uuid, jsonb, boolean) from public, anon, authenticated;

-- Fail the migration rather than committing a mixed 9x9/15x15 state.
do $final_parity$
declare
  v_bad_games integer;
  v_board_cells integer;
begin
  select jsonb_array_length(private.word_siege_new_board_v1()) into v_board_cells;
  if v_board_cells <> 225 then
    raise exception 'word_siege_new_board_not_225';
  end if;

  select count(*) into v_bad_games
  from public.word_siege_games
  where jsonb_typeof(board) <> 'array'
     or jsonb_array_length(board) <> 225;
  if v_bad_games <> 0 then
    raise exception 'word_siege_non_225_games_remaining:%', v_bad_games;
  end if;
end
$final_parity$;

select pg_notify('pgrst', 'reload schema');
