create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  created_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);

create index if not exists direct_messages_pair_created_idx on public.direct_messages (sender_id, receiver_id, created_at desc);
create index if not exists direct_messages_receiver_created_idx on public.direct_messages (receiver_id, created_at desc);

alter table public.direct_messages enable row level security;

create or replace function public.are_friends(p_a uuid, p_b uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.user_id = p_a and f.friend_id = p_b) or (f.user_id = p_b and f.friend_id = p_a))
  );
$$;

revoke all on function public.are_friends(uuid, uuid) from public, anon;
grant execute on function public.are_friends(uuid, uuid) to authenticated, service_role;

drop policy if exists direct_messages_select_friends on public.direct_messages;
create policy direct_messages_select_friends on public.direct_messages
for select to authenticated
using (auth.uid() in (sender_id, receiver_id) and public.are_friends(sender_id, receiver_id));

drop policy if exists direct_messages_insert_friends on public.direct_messages;
create policy direct_messages_insert_friends on public.direct_messages
for insert to authenticated
with check (sender_id = auth.uid() and public.are_friends(sender_id, receiver_id));

drop policy if exists direct_messages_delete_own on public.direct_messages;
create policy direct_messages_delete_own on public.direct_messages
for delete to authenticated
using (sender_id = auth.uid());

grant select, insert, delete on public.direct_messages to authenticated;
grant usage, select on sequence public.direct_messages_id_seq to authenticated;
