-- Competitive Seasons + Persistent Achievements v1
-- Global rating remains permanent. Season rating resets to 1000 each season.
-- Bot matches are excluded. Only real PvP Son Harf and Word Arena results count.

create table if not exists public.competitive_seasons (
  id text primary key,
  name_tr text not null,
  name_en text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'active' check(status in ('active','ended')),
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  check(ends_at>starts_at)
);

create table if not exists public.season_player_stats (
  season_id text not null references public.competitive_seasons(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating integer not null default 1000 check(rating>=100),
  peak_rating integer not null default 1000 check(peak_rating>=100),
  matches integer not null default 0 check(matches>=0),
  wins integer not null default 0 check(wins>=0),
  losses integer not null default 0 check(losses>=0),
  draws integer not null default 0 check(draws>=0),
  valid_words integer not null default 0 check(valid_words>=0),
  updated_at timestamptz not null default now(),
  primary key(season_id,user_id)
);
create index if not exists season_player_stats_rank_idx on public.season_player_stats(season_id,rating desc,wins desc,matches desc);
create index if not exists season_player_stats_user_idx on public.season_player_stats(user_id,season_id);

create table if not exists public.season_match_events (
  id bigint generated by default as identity primary key,
  season_id text not null references public.competitive_seasons(id) on delete cascade,
  source_type text not null check(source_type in ('classic','arena')),
  source_id uuid not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  result text not null check(result in ('win','loss','draw')),
  rating_delta integer not null,
  valid_words integer not null default 0 check(valid_words>=0),
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(source_type,source_id,user_id)
);
create index if not exists season_match_events_user_idx on public.season_match_events(user_id,occurred_at desc);
create index if not exists season_match_events_season_idx on public.season_match_events(season_id,occurred_at desc);

create table if not exists public.season_honors (
  season_id text not null references public.competitive_seasons(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  honor_code text not null,
  label_tr text not null,
  label_en text not null,
  final_rating integer not null,
  rank integer not null default 1,
  created_at timestamptz not null default now(),
  primary key(season_id,user_id,honor_code)
);
create index if not exists season_honors_user_idx on public.season_honors(user_id,created_at desc);

create table if not exists public.achievement_definitions (
  code text primary key,
  icon text not null,
  title_tr text not null,
  title_en text not null,
  description_tr text not null,
  description_en text not null,
  metric text not null,
  target integer not null check(target>0),
  reward_coin integer not null default 0 check(reward_coin>=0),
  sort_order integer not null,
  active boolean not null default true
);

create table if not exists public.achievement_unlocks (
  user_id uuid not null references public.profiles(id) on delete cascade,
  achievement_code text not null references public.achievement_definitions(code) on delete cascade,
  reward_coin integer not null default 0,
  unlocked_at timestamptz not null default now(),
  primary key(user_id,achievement_code)
);
create index if not exists achievement_unlocks_user_time_idx on public.achievement_unlocks(user_id,unlocked_at desc);
create index if not exists achievement_unlocks_code_idx on public.achievement_unlocks(achievement_code);

alter table public.competitive_seasons enable row level security;
alter table public.season_player_stats enable row level security;
alter table public.season_match_events enable row level security;
alter table public.season_honors enable row level security;
alter table public.achievement_definitions enable row level security;
alter table public.achievement_unlocks enable row level security;

revoke all on public.competitive_seasons from anon,authenticated;
revoke all on public.season_player_stats from anon,authenticated;
revoke all on public.season_match_events from anon,authenticated;
revoke all on public.season_honors from anon,authenticated;
revoke all on public.achievement_definitions from anon,authenticated;
revoke all on public.achievement_unlocks from anon,authenticated;

insert into public.competitive_seasons(id,name_tr,name_en,starts_at,ends_at,status)
values(
  'launch-2026',
  'Lansman Sezonu',
  'Launch Season',
  timestamptz '2026-08-29 00:00:00+03',
  timestamptz '2026-10-01 00:00:00+03',
  'active'
)
on conflict(id) do nothing;

insert into public.achievement_definitions(
  code,icon,title_tr,title_en,description_tr,description_en,metric,target,reward_coin,sort_order
) values
('FIRST_DUEL','⚔','İlk Düello','First Duel','İlk rekabetçi maçını tamamla.','Complete your first competitive match.','total_matches',1,20,10),
('FIRST_WIN','🏆','İlk Zafer','First Victory','İlk galibiyetini al.','Earn your first win.','wins',1,20,20),
('WIN_10','🔥','10 Zafer','10 Wins','10 galibiyete ulaş.','Reach 10 wins.','wins',10,30,30),
('WIN_50','👑','50 Zafer','50 Wins','50 galibiyete ulaş.','Reach 50 wins.','wins',50,60,40),
('WORD_100','✦','100 Kelime','100 Words','100 geçerli kelime üret.','Play 100 valid words.','valid_words',100,30,50),
('WORD_500','💎','500 Kelime','500 Words','500 geçerli kelime üret.','Play 500 valid words.','valid_words',500,75,60),
('STREAK_5','⚡','Alev Alan Seri','Hot Streak','En iyi galibiyet serini 5 yap.','Reach a best win streak of 5.','best_streak',5,40,70),
('RATING_1200','🛡','1200 Rating','1200 Rating','Global ratingini 1200’e çıkar.','Reach 1200 global rating.','rating',1200,50,80),
('RATING_1500','⭐','1500 Rating','1500 Rating','Global ratingini 1500’e çıkar.','Reach 1500 global rating.','rating',1500,100,90),
('DUEL_100','🎯','100 Düello','100 Duels','100 rekabetçi maç tamamla.','Complete 100 competitive matches.','total_matches',100,75,100),
('SEASON_GOLD','🌟','Sezon Altın','Season Gold','Bir sezonda 1250 ratinge ulaş.','Reach 1250 rating in a season.','season_peak',1250,60,110),
('SEASON_CHAMPION','🏅','Sezon Şampiyonu','Season Champion','Bir rekabet sezonunu 1. bitir.','Finish a competitive season at rank #1.','season_champion',1,250,120)
on conflict(code) do update set
  icon=excluded.icon,
  title_tr=excluded.title_tr,
  title_en=excluded.title_en,
  description_tr=excluded.description_tr,
  description_en=excluded.description_en,
  metric=excluded.metric,
  target=excluded.target,
  reward_coin=excluded.reward_coin,
  sort_order=excluded.sort_order,
  active=true;

create or replace function public.competitive_season_name_tr_v1(p_start timestamptz)
returns text
language sql
stable
set search_path=public,pg_temp
as $$
  select
    case extract(month from p_start at time zone 'Europe/Istanbul')::int
      when 1 then 'Ocak' when 2 then 'Şubat' when 3 then 'Mart' when 4 then 'Nisan'
      when 5 then 'Mayıs' when 6 then 'Haziran' when 7 then 'Temmuz' when 8 then 'Ağustos'
      when 9 then 'Eylül' when 10 then 'Ekim' when 11 then 'Kasım' else 'Aralık'
    end || ' ' ||
    extract(year from p_start at time zone 'Europe/Istanbul')::int::text ||
    ' Sezonu'
$$;

create or replace function public.ensure_competitive_season_v1(p_reference timestamptz default now())
returns text
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_id text;
  v_local timestamp;
  v_start timestamptz;
  v_end timestamptz;
begin
  perform pg_advisory_xact_lock(88112602);

  insert into public.season_honors(
    season_id,user_id,honor_code,label_tr,label_en,final_rating,rank
  )
  select
    s.id,
    winner.user_id,
    'CHAMPION',
    s.name_tr || ' Şampiyonu',
    s.name_en || ' Champion',
    winner.rating,
    1
  from public.competitive_seasons s
  cross join lateral (
    select ps.user_id,ps.rating
    from public.season_player_stats ps
    where ps.season_id=s.id and ps.matches>0
    order by ps.rating desc,ps.wins desc,ps.matches desc,ps.user_id
    limit 1
  ) winner
  where s.ends_at<=p_reference
    and s.settled_at is null
  on conflict do nothing;

  update public.competitive_seasons
  set status='ended',settled_at=coalesce(settled_at,p_reference)
  where ends_at<=p_reference and settled_at is null;

  select cs.id into v_id
  from public.competitive_seasons cs
  where p_reference>=cs.starts_at and p_reference<cs.ends_at
  order by cs.starts_at desc
  limit 1;

  if v_id is not null then return v_id; end if;

  v_local:=p_reference at time zone 'Europe/Istanbul';
  v_start:=make_timestamptz(
    extract(year from v_local)::int,
    extract(month from v_local)::int,
    1,0,0,0,'Europe/Istanbul'
  );
  v_end:=v_start+interval '1 month';
  v_id:=to_char(v_local,'YYYY-MM');

  insert into public.competitive_seasons(id,name_tr,name_en,starts_at,ends_at,status)
  values(
    v_id,
    public.competitive_season_name_tr_v1(v_start),
    to_char(v_start at time zone 'Europe/Istanbul','FMMonth YYYY') || ' Season',
    v_start,
    v_end,
    'active'
  )
  on conflict(id) do nothing;

  return v_id;
end
$$;

create or replace function public.sync_achievement_unlocks_v1(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  rec record;
  v_reward int:=0;
begin
  if p_user_id is null then return 0; end if;

  for rec in
    with metrics as (
      select
        d.code,
        d.reward_coin,
        d.target,
        case d.metric
          when 'total_matches' then coalesce(p.total_matches,0)
          when 'wins' then coalesce(p.wins,0)
          when 'valid_words' then coalesce(p.valid_words,0)
          when 'best_streak' then coalesce(p.best_streak,0)
          when 'rating' then coalesce(p.rating,1000)
          when 'season_peak' then coalesce((
            select max(ps.peak_rating)
            from public.season_player_stats ps
            where ps.user_id=p_user_id
          ),1000)
          when 'season_champion' then case when exists(
            select 1 from public.season_honors h
            where h.user_id=p_user_id and h.honor_code='CHAMPION'
          ) then 1 else 0 end
          else 0
        end::int as current_value
      from public.achievement_definitions d
      join public.profiles p on p.id=p_user_id
      where d.active
    ),
    inserted as (
      insert into public.achievement_unlocks(user_id,achievement_code,reward_coin)
      select p_user_id,m.code,m.reward_coin
      from metrics m
      where m.current_value>=m.target
      on conflict do nothing
      returning achievement_code,reward_coin
    )
    select * from inserted
  loop
    v_reward:=v_reward+rec.reward_coin;
    if rec.reward_coin>0 then
      insert into public.diamond_ledger(user_id,delta,reason,item_id)
      values(p_user_id,rec.reward_coin,'achievement:'||rec.achievement_code,null);
    end if;
  end loop;

  if v_reward>0 then
    update public.profiles
    set diamonds=coalesce(diamonds,0)+v_reward,updated_at=now()
    where id=p_user_id;
  end if;

  return v_reward;
end
$$;

create or replace function public.record_competitive_result_v1(
  p_source_type text,
  p_source_id uuid,
  p_user_id uuid,
  p_result text,
  p_rating_delta integer,
  p_valid_words integer,
  p_occurred_at timestamptz
)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_season text;
  v_inserted bigint;
  v_before int;
  v_after int;
begin
  if p_user_id is null or p_source_id is null then return; end if;
  if p_source_type not in ('classic','arena') then raise exception 'invalid_source_type'; end if;
  if p_result not in ('win','loss','draw') then raise exception 'invalid_result'; end if;

  select cs.id into v_season
  from public.competitive_seasons cs
  where p_occurred_at>=cs.starts_at and p_occurred_at<cs.ends_at
  order by cs.starts_at desc
  limit 1;

  if v_season is null then
    v_season:=public.ensure_competitive_season_v1(p_occurred_at);
  end if;

  insert into public.season_match_events(
    season_id,source_type,source_id,user_id,result,rating_delta,valid_words,occurred_at
  )
  values(
    v_season,p_source_type,p_source_id,p_user_id,p_result,p_rating_delta,
    greatest(coalesce(p_valid_words,0),0),p_occurred_at
  )
  on conflict(source_type,source_id,user_id) do nothing
  returning id into v_inserted;

  if v_inserted is null then return; end if;

  insert into public.season_player_stats(season_id,user_id)
  values(v_season,p_user_id)
  on conflict do nothing;

  select ps.rating into v_before
  from public.season_player_stats ps
  where ps.season_id=v_season and ps.user_id=p_user_id
  for update;

  v_after:=greatest(100,v_before+p_rating_delta);

  update public.season_player_stats ps
  set rating=v_after,
      peak_rating=greatest(ps.peak_rating,v_after),
      matches=ps.matches+1,
      wins=ps.wins+case when p_result='win' then 1 else 0 end,
      losses=ps.losses+case when p_result='loss' then 1 else 0 end,
      draws=ps.draws+case when p_result='draw' then 1 else 0 end,
      valid_words=ps.valid_words+greatest(coalesce(p_valid_words,0),0),
      updated_at=now()
  where ps.season_id=v_season and ps.user_id=p_user_id;

  perform public.sync_achievement_unlocks_v1(p_user_id);
end
$$;

create or replace function public.capture_classic_season_result_v1()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_when timestamptz:=coalesce(new.finished_at,new.created_at,now());
  v_host_words int:=0;
  v_guest_words int:=0;
begin
  if not new.stats_applied or coalesce(old.stats_applied,false) then return new; end if;
  if new.status<>'finished' or coalesce(new.is_bot,false) or new.guest_id is null then return new; end if;

  select count(*)::int into v_host_words from public.game_words where room_id=new.id and player_id=new.host_id;
  select count(*)::int into v_guest_words from public.game_words where room_id=new.id and player_id=new.guest_id;

  perform public.record_competitive_result_v1(
    'classic',new.id,new.host_id,
    case when new.winner_id is null then 'draw' when new.winner_id=new.host_id then 'win' else 'loss' end,
    case when new.winner_id is null then 0 when new.winner_id=new.host_id then 20 else -15 end,
    v_host_words,v_when
  );
  perform public.record_competitive_result_v1(
    'classic',new.id,new.guest_id,
    case when new.winner_id is null then 'draw' when new.winner_id=new.guest_id then 'win' else 'loss' end,
    case when new.winner_id is null then 0 when new.winner_id=new.guest_id then 20 else -15 end,
    v_guest_words,v_when
  );
  return new;
end
$$;

drop trigger if exists trg_capture_classic_season_result_v1 on public.game_rooms;
create trigger trg_capture_classic_season_result_v1
after update of stats_applied on public.game_rooms
for each row
when (new.stats_applied=true and old.stats_applied is distinct from true)
execute function public.capture_classic_season_result_v1();

create or replace function public.capture_arena_season_result_v1()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_when timestamptz:=coalesce(new.finished_at,new.ends_at,now());
  v_host_words int:=0;
  v_guest_words int:=0;
begin
  if not new.result_applied or coalesce(old.result_applied,false) then return new; end if;
  if new.status<>'finished' then return new; end if;

  select count(*)::int into v_host_words from public.word_arena_words where room_id=new.id and user_id=new.host_id;
  select count(*)::int into v_guest_words from public.word_arena_words where room_id=new.id and user_id=new.guest_id;

  perform public.record_competitive_result_v1(
    'arena',new.id,new.host_id,
    case when new.winner_id is null then 'draw' when new.winner_id=new.host_id then 'win' else 'loss' end,
    case when new.winner_id is null then 0 when new.winner_id=new.host_id then 18 else -12 end,
    v_host_words,v_when
  );
  perform public.record_competitive_result_v1(
    'arena',new.id,new.guest_id,
    case when new.winner_id is null then 'draw' when new.winner_id=new.guest_id then 'win' else 'loss' end,
    case when new.winner_id is null then 0 when new.winner_id=new.guest_id then 18 else -12 end,
    v_guest_words,v_when
  );
  return new;
end
$$;

drop trigger if exists trg_capture_arena_season_result_v1 on public.word_arena_rooms;
create trigger trg_capture_arena_season_result_v1
after update of result_applied on public.word_arena_rooms
for each row
when (new.result_applied=true and old.result_applied is distinct from true)
execute function public.capture_arena_season_result_v1();

create or replace function public.get_competitive_season_v1()
returns table(
  season_id text,
  name_tr text,
  name_en text,
  starts_at timestamptz,
  ends_at timestamptz,
  rating integer,
  peak_rating integer,
  league_name text,
  season_rank bigint,
  player_count bigint,
  matches integer,
  wins integer,
  losses integer,
  draws integer,
  valid_words integer,
  next_rating integer,
  points_to_next integer,
  honor_count bigint,
  latest_honor_tr text,
  latest_honor_en text
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_sid text;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  v_sid:=public.ensure_competitive_season_v1(now());

  insert into public.season_player_stats(season_id,user_id)
  values(v_sid,v_uid)
  on conflict do nothing;

  perform public.sync_achievement_unlocks_v1(v_uid);

  return query
  with ranked as (
    select
      ps.user_id,
      rank() over(order by ps.rating desc,ps.wins desc,ps.matches desc,ps.user_id) rnk,
      count(*) over() cnt
    from public.season_player_stats ps
    where ps.season_id=v_sid and ps.matches>0
  ),
  mine as (
    select ps2.*
    from public.season_player_stats ps2
    where ps2.season_id=v_sid and ps2.user_id=v_uid
  )
  select
    s.id,
    s.name_tr,
    s.name_en,
    s.starts_at,
    s.ends_at,
    m.rating,
    m.peak_rating,
    public.league_for_rating_v1(m.rating),
    coalesce(r.rnk,0)::bigint,
    coalesce((select max(r2.cnt) from ranked r2),0)::bigint,
    m.matches,
    m.wins,
    m.losses,
    m.draws,
    m.valid_words,
    case
      when m.rating<1100 then 1100
      when m.rating<1250 then 1250
      when m.rating<1400 then 1400
      when m.rating<1600 then 1600
      when m.rating<1800 then 1800
      else null
    end,
    case
      when m.rating<1100 then 1100-m.rating
      when m.rating<1250 then 1250-m.rating
      when m.rating<1400 then 1400-m.rating
      when m.rating<1600 then 1600-m.rating
      when m.rating<1800 then 1800-m.rating
      else 0
    end,
    (select count(*) from public.season_honors h where h.user_id=v_uid),
    (select h.label_tr from public.season_honors h where h.user_id=v_uid order by h.created_at desc limit 1),
    (select h.label_en from public.season_honors h where h.user_id=v_uid order by h.created_at desc limit 1)
  from public.competitive_seasons s
  join mine m on true
  left join ranked r on r.user_id=v_uid
  where s.id=v_sid;
end
$$;

create or replace function public.get_season_leaderboard_v1(p_limit integer default 50)
returns table(
  user_id uuid,
  display_name text,
  rating integer,
  peak_rating integer,
  league_name text,
  matches integer,
  wins integer,
  losses integer,
  draws integer,
  win_rate numeric,
  rank_no bigint
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
  v_sid text;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  v_sid:=public.ensure_competitive_season_v1(now());

  return query
  select
    ps.user_id,
    p.display_name,
    ps.rating,
    ps.peak_rating,
    public.league_for_rating_v1(ps.rating),
    ps.matches,
    ps.wins,
    ps.losses,
    ps.draws,
    case when ps.matches=0 then 0 else round(ps.wins*100.0/ps.matches,1) end,
    rank() over(order by ps.rating desc,ps.wins desc,ps.matches desc,ps.user_id)
  from public.season_player_stats ps
  join public.profiles p on p.id=ps.user_id
  where ps.season_id=v_sid and ps.matches>0
  order by ps.rating desc,ps.wins desc,ps.matches desc,ps.user_id
  limit greatest(1,least(coalesce(p_limit,50),100));
end
$$;

create or replace function public.get_achievements_v1()
returns table(
  code text,
  icon text,
  title_tr text,
  title_en text,
  description_tr text,
  description_en text,
  current_value integer,
  target integer,
  reward_coin integer,
  unlocked boolean,
  unlocked_at timestamptz
)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_uid uuid:=auth.uid();
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  perform public.ensure_competitive_season_v1(now());
  perform public.sync_achievement_unlocks_v1(v_uid);

  return query
  select
    d.code,
    d.icon,
    d.title_tr,
    d.title_en,
    d.description_tr,
    d.description_en,
    case d.metric
      when 'total_matches' then coalesce(p.total_matches,0)
      when 'wins' then coalesce(p.wins,0)
      when 'valid_words' then coalesce(p.valid_words,0)
      when 'best_streak' then coalesce(p.best_streak,0)
      when 'rating' then coalesce(p.rating,1000)
      when 'season_peak' then coalesce((select max(ps.peak_rating) from public.season_player_stats ps where ps.user_id=v_uid),1000)
      when 'season_champion' then case when exists(
        select 1 from public.season_honors h where h.user_id=v_uid and h.honor_code='CHAMPION'
      ) then 1 else 0 end
      else 0
    end::int,
    d.target,
    d.reward_coin,
    u.achievement_code is not null,
    u.unlocked_at
  from public.achievement_definitions d
  join public.profiles p on p.id=v_uid
  left join public.achievement_unlocks u on u.user_id=v_uid and u.achievement_code=d.code
  where d.active
  order by d.sort_order,d.code;
end
$$;

revoke all on function public.competitive_season_name_tr_v1(timestamptz) from public,anon,authenticated;
revoke all on function public.ensure_competitive_season_v1(timestamptz) from public,anon,authenticated;
revoke all on function public.sync_achievement_unlocks_v1(uuid) from public,anon,authenticated;
revoke all on function public.record_competitive_result_v1(text,uuid,uuid,text,integer,integer,timestamptz) from public,anon,authenticated;
revoke all on function public.capture_classic_season_result_v1() from public,anon,authenticated;
revoke all on function public.capture_arena_season_result_v1() from public,anon,authenticated;

revoke all on function public.get_competitive_season_v1() from public,anon;
revoke all on function public.get_season_leaderboard_v1(integer) from public,anon;
revoke all on function public.get_achievements_v1() from public,anon;
grant execute on function public.get_competitive_season_v1() to authenticated;
grant execute on function public.get_season_leaderboard_v1(integer) to authenticated;
grant execute on function public.get_achievements_v1() to authenticated;

-- Backfill launch-season results if deployment happens after eligible matches.
do $$
declare r record;
begin
  for r in
    select g.*
    from public.game_rooms g
    where g.status='finished'
      and g.stats_applied
      and not coalesce(g.is_bot,false)
      and g.guest_id is not null
      and coalesce(g.finished_at,g.created_at)>=timestamptz '2026-08-29 00:00:00+03'
      and coalesce(g.finished_at,g.created_at)<timestamptz '2026-10-01 00:00:00+03'
  loop
    perform public.record_competitive_result_v1(
      'classic',r.id,r.host_id,
      case when r.winner_id is null then 'draw' when r.winner_id=r.host_id then 'win' else 'loss' end,
      case when r.winner_id is null then 0 when r.winner_id=r.host_id then 20 else -15 end,
      (select count(*)::int from public.game_words w where w.room_id=r.id and w.player_id=r.host_id),
      coalesce(r.finished_at,r.created_at)
    );
    perform public.record_competitive_result_v1(
      'classic',r.id,r.guest_id,
      case when r.winner_id is null then 'draw' when r.winner_id=r.guest_id then 'win' else 'loss' end,
      case when r.winner_id is null then 0 when r.winner_id=r.guest_id then 20 else -15 end,
      (select count(*)::int from public.game_words w where w.room_id=r.id and w.player_id=r.guest_id),
      coalesce(r.finished_at,r.created_at)
    );
  end loop;

  for r in
    select a.*
    from public.word_arena_rooms a
    where a.status='finished'
      and a.result_applied
      and coalesce(a.finished_at,a.ends_at)>=timestamptz '2026-08-29 00:00:00+03'
      and coalesce(a.finished_at,a.ends_at)<timestamptz '2026-10-01 00:00:00+03'
  loop
    perform public.record_competitive_result_v1(
      'arena',r.id,r.host_id,
      case when r.winner_id is null then 'draw' when r.winner_id=r.host_id then 'win' else 'loss' end,
      case when r.winner_id is null then 0 when r.winner_id=r.host_id then 18 else -12 end,
      (select count(*)::int from public.word_arena_words w where w.room_id=r.id and w.user_id=r.host_id),
      coalesce(r.finished_at,r.ends_at)
    );
    perform public.record_competitive_result_v1(
      'arena',r.id,r.guest_id,
      case when r.winner_id is null then 'draw' when r.winner_id=r.guest_id then 'win' else 'loss' end,
      case when r.winner_id is null then 0 when r.winner_id=r.guest_id then 18 else -12 end,
      (select count(*)::int from public.word_arena_words w where w.room_id=r.id and w.user_id=r.guest_id),
      coalesce(r.finished_at,r.ends_at)
    );
  end loop;
end
$$;
