-- Word Siege v4: canonical 15x15 / 225-cell board geometry.
-- Scoring semantics are unchanged: word points are permanent and each currently owned cube is worth 2.

create or replace function private.word_siege_new_board_v1()
returns jsonb
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  select jsonb_agg(
    jsonb_build_object(
      'letter', null,
      'owner', 0,
      'bonus', case
        when i in (0,7,14,105,119,210,217,224) then '3K'
        when i in (20,24,76,80,84,88,136,140,144,148,200,204) then '3H'
        when i in (16,28,32,42,48,56,64,70,112,154,160,168,176,182,192,196,208) then '2K'
        when i in (3,11,36,38,45,52,59,92,96,98,102,108,116,122,126,128,132,165,172,179,186,188,213,221) then '2H'
        else null
      end,
      'bonus_used', false
    ) order by i
  )
  from generate_series(0, 224) i
$$;

-- Remap historical 9x9 move coordinates into the centered 9x9 region of the new 15x15 board.
update public.word_siege_moves m
set placed_tiles = (
  select coalesce(jsonb_agg(
    tile || jsonb_build_object(
      'index', ((((tile ->> 'index')::integer / 9) + 3) * 15) + (((tile ->> 'index')::integer % 9) + 3)
    ) order by ordinality
  ), '[]'::jsonb)
  from jsonb_array_elements(m.placed_tiles) with ordinality as t(tile, ordinality)
)
where exists (
  select 1 from public.word_siege_games g
  where g.id = m.game_id and jsonb_array_length(g.board) = 81
);

-- Preserve existing letters/owners while centering legacy 9x9 games inside the new board.
update public.word_siege_games g
set board = (
  with fresh as (select private.word_siege_new_board_v1() as board)
  select jsonb_agg(
    case
      when (i / 15) between 3 and 11 and (i % 15) between 3 and 11 then
        (fresh.board -> i) || jsonb_build_object(
          'letter', g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'letter',
          'owner', coalesce(g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'owner', '0'::jsonb),
          'bonus_used', coalesce(g.board -> ((((i / 15) - 3) * 9) + ((i % 15) - 3)) -> 'bonus_used', 'false'::jsonb)
        )
      else fresh.board -> i
    end
    order by i
  )
  from fresh, generate_series(0, 224) i
)
where jsonb_typeof(g.board) = 'array' and jsonb_array_length(g.board) = 81;

-- Replace legacy 81-cell checks without relying on autogenerated constraint names.
do $$
declare c record;
begin
  for c in
    select conname, pg_get_constraintdef(oid) as definition
    from pg_constraint
    where conrelid = 'public.word_siege_games'::regclass and contype = 'c'
  loop
    if c.definition like '%player_one_area%81%'
       or c.definition like '%player_two_area%81%'
       or c.definition like '%jsonb_array_length(board)%81%' then
      execute format('alter table public.word_siege_games drop constraint %I', c.conname);
    end if;
  end loop;
end $$;

alter table public.word_siege_games drop constraint if exists word_siege_games_player_one_area_v4_check;
alter table public.word_siege_games drop constraint if exists word_siege_games_player_two_area_v4_check;
alter table public.word_siege_games drop constraint if exists word_siege_games_board_v4_check;
alter table public.word_siege_games
  add constraint word_siege_games_player_one_area_v4_check check (player_one_area between 0 and 225),
  add constraint word_siege_games_player_two_area_v4_check check (player_two_area between 0 and 225),
  add constraint word_siege_games_board_v4_check check (jsonb_typeof(board) = 'array' and jsonb_array_length(board) = 225);

create or replace function private.word_siege_collect_cells_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_anchor integer,
  p_delta integer
)
returns integer[]
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_start integer := p_anchor;
  v_current integer;
  v_next integer;
  v_cells integer[] := array[]::integer[];
begin
  if p_delta not in (1, 15) or p_anchor not between 0 and 224 then return v_cells; end if;
  if private.word_siege_letter_at_v1(p_board, p_placements, p_rack, p_anchor) is null then return v_cells; end if;

  loop
    v_next := v_start - p_delta;
    exit when v_next < 0;
    exit when p_delta = 1 and (v_next / 15) <> (v_start / 15);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_next) is null;
    v_start := v_next;
  end loop;

  v_current := v_start;
  loop
    exit when v_current > 224;
    exit when p_delta = 1 and (v_current / 15) <> (v_start / 15);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_current) is null;
    v_cells := array_append(v_cells, v_current);
    v_next := v_current + p_delta;
    exit when v_next > 224;
    exit when p_delta = 1 and (v_next / 15) <> (v_current / 15);
    v_current := v_next;
  end loop;
  return v_cells;
end
$$;

create or replace function private.word_siege_word_allowed_v1(p_word text, p_language text)
returns boolean
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_language text := case when lower(coalesce(p_language, 'tr')) = 'en' then 'en' else 'tr' end;
  v_normalized text;
begin
  v_normalized := public.normalize_game_word(v_language, trim(coalesce(p_word, '')));
  if char_length(v_normalized) not between 2 and 15 then return false; end if;
  if v_language = 'tr' and (left(v_normalized, 1) = 'ğ' or right(v_normalized, 1) = 'ğ') then return false; end if;
  return exists (
    select 1 from public.dictionary_words d
    where d.language = v_language and d.active and d.normalized_word = v_normalized
  );
end
$$;

create or replace function private.word_siege_area_delta_v1(
  p_before_board jsonb,
  p_after_board jsonb,
  p_owner integer
)
returns table(neutral_captured integer, opponent_captured integer, area_score integer)
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  with ownership as (
    select i,
      coalesce((p_before_board -> i ->> 'owner')::integer, 0) as before_owner,
      coalesce((p_after_board -> i ->> 'owner')::integer, 0) as after_owner
    from generate_series(0, 224) i
  ), counts as (
    select
      count(*) filter (where before_owner = 0 and after_owner = p_owner)::integer as neutral_count,
      count(*) filter (where before_owner not in (0, p_owner) and after_owner = p_owner)::integer as opponent_count
    from ownership
  )
  select neutral_count, opponent_count, (neutral_count + opponent_count) * 2 from counts
$$;

create or replace function private.submit_word_siege_move_v1(
  p_game_id uuid,
  p_placements jsonb,
  p_horizontal boolean default true
)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_board jsonb;
  v_before_board jsonb;
  v_rack text;
  v_bag text;
  v_owner integer;
  v_other uuid;
  v_indices integer[];
  v_rack_indices integer[];
  v_anchor integer;
  v_main_cells integer[];
  v_cross_cells integer[];
  v_words text[] := array[]::text[];
  v_word text;
  v_primary text;
  v_score integer := 0;
  v_index integer;
  v_i integer;
  v_distinct integer;
  v_existing boolean;
  v_connected boolean := false;
  v_cell jsonb;
  v_captured integer[] := array[]::integer[];
  v_placed jsonb := '[]'::jsonb;
  v_letter text;
  v_remaining text;
  v_draw text;
  v_next_rack text;
  v_needed integer;
  v_one_area integer;
  v_two_area integer;
  v_neutral_captured integer := 0;
  v_opponent_captured integer := 0;
  v_area_score integer := 0;
  v_request_fingerprint text;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  if p_placements is null or jsonb_typeof(p_placements) <> 'array'
     or jsonb_array_length(p_placements) not between 1 and 7 then raise exception 'word_siege_invalid_placements'; end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;
  if r.current_player_id <> v_uid then raise exception 'word_siege_not_your_turn'; end if;

  v_board := r.board;
  v_before_board := r.board;
  v_bag := r.bag;
  v_owner := case when v_uid = r.player_one_id then 1 else 2 end;
  v_other := case when v_uid = r.player_one_id then r.player_two_id else r.player_one_id end;
  v_rack := case when v_owner = 1 then r.player_one_rack else r.player_two_rack end;
  v_request_fingerprint := md5(p_placements::text || ':' || coalesce(p_horizontal, true)::text);

  select array_agg((e ->> 'index')::integer order by ordinality),
         array_agg((e ->> 'rack_index')::integer order by ordinality)
  into v_indices, v_rack_indices
  from jsonb_array_elements(p_placements) with ordinality as x(e, ordinality);
  if v_indices is null or cardinality(v_indices) <> jsonb_array_length(p_placements) then raise exception 'word_siege_invalid_placements'; end if;
  if exists (select 1 from unnest(v_indices) x where x not between 0 and 224) then raise exception 'word_siege_invalid_cell'; end if;
  if exists (select 1 from unnest(v_rack_indices) x where x < 0 or x >= char_length(coalesce(v_rack, ''))) then raise exception 'word_siege_invalid_rack_tile'; end if;
  select count(distinct x)::integer into v_distinct from unnest(v_indices) x;
  if v_distinct <> cardinality(v_indices) then raise exception 'word_siege_duplicate_cell'; end if;
  select count(distinct x)::integer into v_distinct from unnest(v_rack_indices) x;
  if v_distinct <> cardinality(v_rack_indices) then raise exception 'word_siege_duplicate_rack_tile'; end if;

  foreach v_index in array v_indices loop
    if (v_board -> v_index ->> 'letter') is not null then raise exception 'word_siege_cell_occupied'; end if;
  end loop;

  v_anchor := v_indices[1];
  if cardinality(v_indices) > 1 then
    if p_horizontal and exists (select 1 from unnest(v_indices) x where x / 15 <> v_anchor / 15) then raise exception 'word_siege_not_in_one_row'; end if;
    if not p_horizontal and exists (select 1 from unnest(v_indices) x where x % 15 <> v_anchor % 15) then raise exception 'word_siege_not_in_one_column'; end if;
  end if;

  v_main_cells := private.word_siege_collect_cells_v1(v_board, p_placements, v_rack, v_anchor, case when p_horizontal then 1 else 15 end);
  if exists (select 1 from unnest(v_indices) x where not (x = any(v_main_cells))) then raise exception 'word_siege_gap_between_tiles'; end if;

  select exists (select 1 from jsonb_array_elements(v_board) cell where cell ->> 'letter' is not null) into v_existing;
  if not v_existing and not (112 = any(v_indices)) then raise exception 'word_siege_first_word_must_cover_center'; end if;
  if v_existing and exists (select 1 from unnest(v_main_cells) x where (v_board -> x ->> 'letter') is not null) then v_connected := true; end if;

  if cardinality(v_main_cells) > 1 then
    v_word := private.word_siege_word_from_cells_v1(v_board, p_placements, v_rack, v_main_cells);
    if not private.word_siege_word_allowed_v1(v_word, r.language) then raise exception 'word_siege_invalid_word:%', v_word; end if;
    v_words := array_append(v_words, v_word);
    v_primary := v_word;
    v_score := v_score + private.word_siege_score_word_v1(v_board, p_placements, v_rack, v_main_cells);
    foreach v_index in array v_main_cells loop
      v_cell := v_board -> v_index;
      if (v_cell ->> 'letter') is not null and coalesce((v_cell ->> 'owner')::integer, 0) not in (0, v_owner) then
        v_board := jsonb_set(v_board, array[v_index::text], v_cell || jsonb_build_object('owner', v_owner), false);
        v_captured := array_append(v_captured, v_index);
      end if;
    end loop;
  end if;

  foreach v_index in array v_indices loop
    v_cross_cells := private.word_siege_collect_cells_v1(v_board, p_placements, v_rack, v_index, case when p_horizontal then 15 else 1 end);
    if cardinality(v_cross_cells) > 1 then
      v_connected := v_connected or v_existing;
      v_word := private.word_siege_word_from_cells_v1(v_board, p_placements, v_rack, v_cross_cells);
      if not private.word_siege_word_allowed_v1(v_word, r.language) then raise exception 'word_siege_invalid_word:%', v_word; end if;
      v_words := array_append(v_words, v_word);
      if v_primary is null then v_primary := v_word; end if;
      v_score := v_score + private.word_siege_score_word_v1(v_board, p_placements, v_rack, v_cross_cells);
      foreach v_i in array v_cross_cells loop
        v_cell := v_board -> v_i;
        if (v_cell ->> 'letter') is not null
           and coalesce((v_cell ->> 'owner')::integer, 0) not in (0, v_owner)
           and not (v_i = any(v_captured)) then
          v_board := jsonb_set(v_board, array[v_i::text], v_cell || jsonb_build_object('owner', v_owner), false);
          v_captured := array_append(v_captured, v_i);
        end if;
      end loop;
    end if;
  end loop;

  if cardinality(v_words) = 0 then raise exception 'word_siege_word_required'; end if;
  if v_existing and not v_connected then raise exception 'word_siege_move_must_connect'; end if;

  for v_i in 1..cardinality(v_indices) loop
    v_index := v_indices[v_i];
    v_letter := substring(v_rack from (v_rack_indices[v_i] + 1) for 1);
    v_cell := v_board -> v_index;
    v_board := jsonb_set(v_board, array[v_index::text], v_cell || jsonb_build_object('letter', v_letter, 'owner', v_owner, 'bonus_used', true), false);
    v_placed := v_placed || jsonb_build_array(jsonb_build_object('index', v_index, 'letter', v_letter, 'owner', v_owner));
  end loop;

  select d.neutral_captured, d.opponent_captured, d.area_score
  into v_neutral_captured, v_opponent_captured, v_area_score
  from private.word_siege_area_delta_v1(v_before_board, v_board, v_owner) d;

  select coalesce(string_agg(substring(v_rack from (i + 1) for 1), '' order by i), '') into v_remaining
  from generate_series(0, char_length(v_rack) - 1) i where not (i = any(v_rack_indices));
  v_needed := greatest(0, 7 - char_length(v_remaining));
  v_draw := substring(v_bag from 1 for v_needed);
  v_next_rack := v_remaining || v_draw;
  v_bag := substring(v_bag from (char_length(v_draw) + 1));

  select count(*) filter (where coalesce((cell ->> 'owner')::integer, 0) = 1)::integer,
         count(*) filter (where coalesce((cell ->> 'owner')::integer, 0) = 2)::integer
  into v_one_area, v_two_area from jsonb_array_elements(v_board) cell;

  update public.word_siege_games
  set board = v_board,
      bag = v_bag,
      player_one_rack = case when v_owner = 1 then v_next_rack else player_one_rack end,
      player_two_rack = case when v_owner = 2 then v_next_rack else player_two_rack end,
      player_one_word_score = player_one_word_score + case when v_owner = 1 then v_score else 0 end,
      player_two_word_score = player_two_word_score + case when v_owner = 2 then v_score else 0 end,
      player_one_area_score = player_one_area_score + case when v_owner = 1 then v_area_score else 0 end,
      player_two_area_score = player_two_area_score + case when v_owner = 2 then v_area_score else 0 end,
      player_one_area = v_one_area,
      player_two_area = v_two_area,
      current_player_id = v_other,
      consecutive_passes = 0,
      move_count = move_count + 1,
      last_action = 'word:' || v_primary,
      last_action_player_id = v_uid,
      last_move_at = now(),
      updated_at = now()
  where id = r.id returning * into r;

  insert into public.word_siege_moves(
    game_id, player_id, primary_word, formed_words, placed_tiles, word_score,
    neutral_captured, opponent_captured, area_score, total_score, captured_cells,
    move_number, request_fingerprint
  ) values (
    r.id, v_uid, v_primary, v_words, v_placed, v_score,
    v_neutral_captured, v_opponent_captured, v_area_score, v_score + v_area_score,
    v_neutral_captured + v_opponent_captured, r.move_count, v_request_fingerprint
  );

  if r.bag = '' and v_next_rack = '' then r := private.finish_word_siege_game_v1(r.id, 'rack_empty', null); end if;
  return r;
end
$$;

revoke all on function private.word_siege_new_board_v1() from public, anon, authenticated;
revoke all on function private.word_siege_collect_cells_v1(jsonb, jsonb, text, integer, integer) from public, anon, authenticated;
revoke all on function private.word_siege_word_allowed_v1(text, text) from public, anon, authenticated;
revoke all on function private.word_siege_area_delta_v1(jsonb, jsonb, integer) from public, anon, authenticated;
revoke all on function private.submit_word_siege_move_v1(uuid, jsonb, boolean) from public, anon, authenticated;
select pg_notify('pgrst', 'reload schema');
