-- Kelime Kusatmasi v1: unlimited-time asynchronous 1v1 territory word game.
-- The server owns the bag, racks, board validation, bonuses, scoring and territory.

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create table if not exists public.word_siege_games (
  id uuid primary key default gen_random_uuid(),
  player_one_id uuid not null references public.profiles(id) on delete cascade,
  player_two_id uuid references public.profiles(id) on delete set null,
  status text not null default 'waiting'
    check (status in ('waiting', 'playing', 'finished', 'cancelled')),
  language text not null default 'tr' check (language in ('tr', 'en')),
  current_player_id uuid references public.profiles(id) on delete set null,
  winner_id uuid references public.profiles(id) on delete set null,
  board jsonb not null,
  bag text not null,
  player_one_rack text not null,
  player_two_rack text,
  player_one_word_score integer not null default 0 check (player_one_word_score >= 0),
  player_two_word_score integer not null default 0 check (player_two_word_score >= 0),
  player_one_area integer not null default 0 check (player_one_area between 0 and 81),
  player_two_area integer not null default 0 check (player_two_area between 0 and 81),
  consecutive_passes integer not null default 0 check (consecutive_passes between 0 and 2),
  move_count integer not null default 0 check (move_count >= 0),
  last_action text,
  last_action_player_id uuid references public.profiles(id) on delete set null,
  last_move_at timestamptz,
  finish_reason text,
  result_applied boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  check (player_two_id is null or player_two_id <> player_one_id),
  check (jsonb_typeof(board) = 'array' and jsonb_array_length(board) = 81)
);

create table if not exists public.word_siege_moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.word_siege_games(id) on delete cascade,
  player_id uuid not null references public.profiles(id) on delete cascade,
  primary_word text not null,
  formed_words text[] not null,
  placed_tiles jsonb not null,
  word_score integer not null check (word_score >= 0),
  captured_cells integer not null default 0 check (captured_cells >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.word_siege_messages (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.word_siege_games(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 300),
  created_at timestamptz not null default now()
);

create index if not exists word_siege_games_player_one_updated_idx
  on public.word_siege_games(player_one_id, updated_at desc);
create index if not exists word_siege_games_player_two_updated_idx
  on public.word_siege_games(player_two_id, updated_at desc)
  where player_two_id is not null;
create index if not exists word_siege_games_waiting_idx
  on public.word_siege_games(language, created_at)
  where status = 'waiting';
create index if not exists word_siege_games_turn_idx
  on public.word_siege_games(current_player_id, updated_at desc)
  where status = 'playing';
create index if not exists word_siege_moves_game_created_idx
  on public.word_siege_moves(game_id, created_at, id);
create index if not exists word_siege_moves_player_idx
  on public.word_siege_moves(player_id, created_at desc);
create index if not exists word_siege_messages_game_created_idx
  on public.word_siege_messages(game_id, created_at, id);
create index if not exists word_siege_messages_sender_idx
  on public.word_siege_messages(sender_id, created_at desc);

alter table public.word_siege_games enable row level security;
alter table public.word_siege_moves enable row level security;
alter table public.word_siege_messages enable row level security;

revoke all on public.word_siege_games from anon, authenticated;
revoke all on public.word_siege_moves from anon, authenticated;
revoke all on public.word_siege_messages from anon, authenticated;

drop policy if exists word_siege_games_participants_read on public.word_siege_games;
create policy word_siege_games_participants_read
on public.word_siege_games
for select
to authenticated
using ((select auth.uid()) in (player_one_id, player_two_id));

drop policy if exists word_siege_moves_participants_read on public.word_siege_moves;
create policy word_siege_moves_participants_read
on public.word_siege_moves
for select
to authenticated
using (
  exists (
    select 1
    from public.word_siege_games g
    where g.id = word_siege_moves.game_id
      and (select auth.uid()) in (g.player_one_id, g.player_two_id)
  )
);

drop policy if exists word_siege_messages_participants_read on public.word_siege_messages;
create policy word_siege_messages_participants_read
on public.word_siege_messages
for select
to authenticated
using (
  exists (
    select 1
    from public.word_siege_games g
    where g.id = word_siege_messages.game_id
      and (select auth.uid()) in (g.player_one_id, g.player_two_id)
  )
);

drop policy if exists word_siege_messages_sender_insert on public.word_siege_messages;
create policy word_siege_messages_sender_insert
on public.word_siege_messages
for insert
to authenticated
with check (
  sender_id = (select auth.uid())
  and char_length(btrim(body)) between 1 and 300
  and exists (
    select 1
    from public.word_siege_games g
    where g.id = word_siege_messages.game_id
      and g.status in ('playing', 'finished')
      and (select auth.uid()) in (g.player_one_id, g.player_two_id)
      and not exists (
        select 1
        from public.user_blocks b
        where (b.blocker_id = g.player_one_id and b.blocked_id = g.player_two_id)
           or (b.blocker_id = g.player_two_id and b.blocked_id = g.player_one_id)
      )
  )
  and exists (
    select 1
    from public.profiles p
    where p.id = (select auth.uid())
      and coalesce(p.allow_match_chat, true)
      and (p.chat_suspended_until is null or p.chat_suspended_until <= now())
  )
);

grant select on public.word_siege_games to authenticated;
grant select on public.word_siege_moves to authenticated;
grant select, insert on public.word_siege_messages to authenticated;
grant usage, select on sequence public.word_siege_moves_id_seq to authenticated;
grant usage, select on sequence public.word_siege_messages_id_seq to authenticated;

create or replace function private.word_siege_new_board_v1()
returns jsonb
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  select jsonb_agg(
    jsonb_build_object(
      'letter', null,
      'owner', 0,
      'bonus', case
        when i in (0, 8, 72, 80) then '3K'
        when i in (4, 36, 44, 76) then '3H'
        when i in (10, 16, 64, 70) then '2K'
        when i in (20, 24, 56, 60) then '2H'
        when i = 40 then '2K'
        else null
      end,
      'bonus_used', false
    )
    order by i
  )
  from generate_series(0, 80) i
$$;

create or replace function private.word_siege_shuffle_text_v1(p_text text)
returns text
language sql
volatile
set search_path = pg_catalog, public, private, pg_temp
as $$
  select coalesce(string_agg(ch, '' order by random()), '')
  from regexp_split_to_table(coalesce(p_text, ''), '') ch
  where ch <> ''
$$;

create or replace function private.word_siege_new_bag_v1(p_language text)
returns text
language plpgsql
volatile
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_letters text;
begin
  if lower(coalesce(p_language, 'tr')) = 'en' then
    v_letters := repeat('E', 12) || repeat('A', 9) || repeat('I', 9) || repeat('O', 8) ||
      repeat('N', 6) || repeat('R', 6) || repeat('T', 6) || repeat('L', 4) || repeat('S', 4) ||
      repeat('U', 4) || repeat('D', 4) || repeat('G', 3) || repeat('B', 2) || repeat('C', 2) ||
      repeat('M', 2) || repeat('P', 2) || repeat('F', 2) || repeat('H', 2) || repeat('V', 2) ||
      repeat('W', 2) || repeat('Y', 2) || 'KJXQZ';
  else
    v_letters := repeat('A', 12) || repeat('B', 2) || repeat('C', 2) || repeat('Ç', 2) ||
      repeat('D', 2) || repeat('E', 8) || 'F' || 'G' || 'Ğ' || 'H' || repeat('I', 4) ||
      repeat('İ', 7) || 'J' || repeat('K', 7) || repeat('L', 7) || repeat('M', 4) ||
      repeat('N', 5) || repeat('O', 3) || 'Ö' || 'P' || repeat('R', 6) || repeat('S', 3) ||
      repeat('Ş', 2) || repeat('T', 5) || repeat('U', 3) || repeat('Ü', 2) || 'V' ||
      repeat('Y', 2) || repeat('Z', 2);
  end if;
  return private.word_siege_shuffle_text_v1(v_letters);
end
$$;

create or replace function private.word_siege_letter_value_v1(p_letter text)
returns integer
language sql
immutable
set search_path = pg_catalog, public, private, pg_temp
as $$
  select case coalesce(p_letter, '')
    when 'A' then 1 when 'B' then 3 when 'C' then 4 when 'Ç' then 4
    when 'D' then 3 when 'E' then 1 when 'F' then 7 when 'G' then 5
    when 'Ğ' then 8 when 'H' then 5 when 'I' then 2 when 'İ' then 1
    when 'J' then 10 when 'K' then 1 when 'L' then 1 when 'M' then 2
    when 'N' then 1 when 'O' then 2 when 'Ö' then 7 when 'P' then 5
    when 'R' then 1 when 'S' then 2 when 'Ş' then 4 when 'T' then 1
    when 'U' then 2 when 'Ü' then 3 when 'V' then 7 when 'Y' then 3
    when 'Z' then 4
    else 1
  end
$$;

create or replace function private.word_siege_letter_at_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_index integer
)
returns text
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_letter text;
begin
  select substring(p_rack from ((e ->> 'rack_index')::integer + 1) for 1)
  into v_letter
  from jsonb_array_elements(p_placements) e
  where (e ->> 'index')::integer = p_index
  limit 1;

  if v_letter is not null then return v_letter; end if;
  return nullif(p_board -> p_index ->> 'letter', '');
end
$$;

create or replace function private.word_siege_collect_cells_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_anchor integer,
  p_delta integer
)
returns integer[]
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_start integer := p_anchor;
  v_current integer;
  v_next integer;
  v_cells integer[] := array[]::integer[];
begin
  if p_delta not in (1, 9) or p_anchor not between 0 and 80 then
    return v_cells;
  end if;
  if private.word_siege_letter_at_v1(p_board, p_placements, p_rack, p_anchor) is null then
    return v_cells;
  end if;

  loop
    v_next := v_start - p_delta;
    exit when v_next < 0;
    exit when p_delta = 1 and (v_next / 9) <> (v_start / 9);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_next) is null;
    v_start := v_next;
  end loop;

  v_current := v_start;
  loop
    exit when v_current > 80;
    exit when p_delta = 1 and (v_current / 9) <> (v_start / 9);
    exit when private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_current) is null;
    v_cells := array_append(v_cells, v_current);
    v_next := v_current + p_delta;
    exit when v_next > 80;
    exit when p_delta = 1 and (v_next / 9) <> (v_current / 9);
    v_current := v_next;
  end loop;
  return v_cells;
end
$$;

create or replace function private.word_siege_word_from_cells_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_cells integer[]
)
returns text
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_index integer;
  v_word text := '';
begin
  foreach v_index in array p_cells loop
    v_word := v_word || coalesce(
      private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_index),
      ''
    );
  end loop;
  return v_word;
end
$$;

create or replace function private.word_siege_word_allowed_v1(p_word text, p_language text)
returns boolean
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_language text := case when lower(coalesce(p_language, 'tr')) = 'en' then 'en' else 'tr' end;
  v_normalized text;
begin
  v_normalized := public.normalize_game_word(v_language, trim(coalesce(p_word, '')));
  if char_length(v_normalized) not between 2 and 9 then return false; end if;
  if v_language = 'tr' and (left(v_normalized, 1) = 'ğ' or right(v_normalized, 1) = 'ğ') then
    return false;
  end if;
  return exists (
    select 1
    from public.dictionary_words d
    where d.language = v_language
      and d.active
      and d.normalized_word = v_normalized
  );
end
$$;

create or replace function private.word_siege_score_word_v1(
  p_board jsonb,
  p_placements jsonb,
  p_rack text,
  p_cells integer[]
)
returns integer
language plpgsql
stable
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_index integer;
  v_cell jsonb;
  v_letter text;
  v_bonus text;
  v_letter_score integer;
  v_word_multiplier integer := 1;
  v_total integer := 0;
  v_is_new boolean;
begin
  foreach v_index in array p_cells loop
    v_cell := p_board -> v_index;
    v_letter := private.word_siege_letter_at_v1(p_board, p_placements, p_rack, v_index);
    v_letter_score := private.word_siege_letter_value_v1(v_letter);
    v_is_new := (v_cell ->> 'letter') is null;
    v_bonus := case
      when v_is_new and not coalesce((v_cell ->> 'bonus_used')::boolean, false)
        then v_cell ->> 'bonus'
      else null
    end;
    if v_bonus = '2H' then v_letter_score := v_letter_score * 2; end if;
    if v_bonus = '3H' then v_letter_score := v_letter_score * 3; end if;
    if v_bonus = '2K' then v_word_multiplier := v_word_multiplier * 2; end if;
    if v_bonus = '3K' then v_word_multiplier := v_word_multiplier * 3; end if;
    v_total := v_total + v_letter_score;
  end loop;
  return v_total * v_word_multiplier;
end
$$;

create or replace function private.finish_word_siege_game_v1(
  p_game_id uuid,
  p_reason text,
  p_forfeit_winner uuid default null
)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_winner uuid;
  v_one_total integer;
  v_two_total integer;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  select * into r
  from public.word_siege_games
  where id = p_game_id
  for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status = 'finished' then return r; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;

  v_one_total := r.player_one_word_score + r.player_one_area;
  v_two_total := r.player_two_word_score + r.player_two_area;
  if p_forfeit_winner is not null then
    if p_forfeit_winner not in (r.player_one_id, r.player_two_id) then
      raise exception 'word_siege_invalid_winner';
    end if;
    v_winner := p_forfeit_winner;
  else
    v_winner := case
      when v_one_total > v_two_total then r.player_one_id
      when v_two_total > v_one_total then r.player_two_id
      when r.player_one_area > r.player_two_area then r.player_one_id
      when r.player_two_area > r.player_one_area then r.player_two_id
      else null
    end;
  end if;

  update public.word_siege_games
  set status = 'finished',
      current_player_id = null,
      winner_id = v_winner,
      finish_reason = left(coalesce(p_reason, 'completed'), 40),
      result_applied = true,
      finished_at = now(),
      updated_at = now()
  where id = r.id
  returning * into r;
  return r;
end
$$;

create or replace function private.find_or_create_word_siege_game_v1(p_language text default 'tr')
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_language text := case when lower(coalesce(p_language, 'tr')) = 'en' then 'en' else 'tr' end;
  v_bag text;
  v_rack text;
  v_active_count integer;
  r public.word_siege_games;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  if not exists (select 1 from public.profiles p where p.id = v_uid) then
    raise exception 'word_siege_profile_required';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('word_siege:' || v_language, 0));

  select count(*)::integer into v_active_count
  from public.word_siege_games g
  where g.status in ('waiting', 'playing')
    and v_uid in (g.player_one_id, g.player_two_id);
  if v_active_count >= 10 then raise exception 'word_siege_active_limit'; end if;

  select * into r
  from public.word_siege_games g
  where g.status = 'waiting'
    and g.player_one_id = v_uid
    and g.language = v_language
  order by g.created_at
  limit 1;
  if r.id is not null then return r; end if;

  select * into r
  from public.word_siege_games g
  where g.status = 'waiting'
    and g.language = v_language
    and g.player_one_id <> v_uid
    and not exists (
      select 1
      from public.user_blocks b
      where (b.blocker_id = v_uid and b.blocked_id = g.player_one_id)
         or (b.blocker_id = g.player_one_id and b.blocked_id = v_uid)
    )
  order by g.created_at
  for update skip locked
  limit 1;

  if r.id is not null then
    update public.word_siege_games
    set player_two_id = v_uid,
        player_two_rack = substring(r.bag from 1 for 7),
        bag = substring(r.bag from 8),
        status = 'playing',
        current_player_id = r.player_one_id,
        last_action = 'game_started',
        updated_at = now()
    where id = r.id
    returning * into r;
    return r;
  end if;

  v_bag := private.word_siege_new_bag_v1(v_language);
  v_rack := substring(v_bag from 1 for 7);
  v_bag := substring(v_bag from 8);
  insert into public.word_siege_games(
    player_one_id, language, board, bag, player_one_rack, last_action
  ) values (
    v_uid, v_language, private.word_siege_new_board_v1(), v_bag, v_rack, 'waiting_for_opponent'
  )
  returning * into r;
  return r;
end
$$;

create or replace function private.cancel_word_siege_waiting_v1(p_game_id uuid)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if r.player_one_id <> v_uid then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'waiting' then raise exception 'word_siege_not_waiting'; end if;
  update public.word_siege_games
  set status = 'cancelled', last_action = 'waiting_cancelled',
      last_action_player_id = v_uid, updated_at = now(), finished_at = now(),
      finish_reason = 'cancelled'
  where id = r.id
  returning * into r;
  return r;
end
$$;

create or replace function private.submit_word_siege_move_v1(
  p_game_id uuid,
  p_placements jsonb,
  p_horizontal boolean default true
)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_board jsonb;
  v_rack text;
  v_bag text;
  v_owner integer;
  v_other uuid;
  v_indices integer[];
  v_rack_indices integer[];
  v_anchor integer;
  v_main_cells integer[];
  v_cross_cells integer[];
  v_cells integer[];
  v_words text[] := array[]::text[];
  v_word text;
  v_primary text;
  v_score integer := 0;
  v_index integer;
  v_i integer;
  v_distinct integer;
  v_existing boolean;
  v_connected boolean := false;
  v_cell jsonb;
  v_captured integer[] := array[]::integer[];
  v_placed jsonb := '[]'::jsonb;
  v_letter text;
  v_remaining text;
  v_draw text;
  v_next_rack text;
  v_needed integer;
  v_one_area integer;
  v_two_area integer;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  if p_placements is null or jsonb_typeof(p_placements) <> 'array'
     or jsonb_array_length(p_placements) not between 1 and 7 then
    raise exception 'word_siege_invalid_placements';
  end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;
  if r.current_player_id <> v_uid then raise exception 'word_siege_not_your_turn'; end if;

  v_board := r.board;
  v_bag := r.bag;
  v_owner := case when v_uid = r.player_one_id then 1 else 2 end;
  v_other := case when v_uid = r.player_one_id then r.player_two_id else r.player_one_id end;
  v_rack := case when v_owner = 1 then r.player_one_rack else r.player_two_rack end;

  select array_agg((e ->> 'index')::integer order by ordinality),
         array_agg((e ->> 'rack_index')::integer order by ordinality)
  into v_indices, v_rack_indices
  from jsonb_array_elements(p_placements) with ordinality as x(e, ordinality);
  if v_indices is null or cardinality(v_indices) <> jsonb_array_length(p_placements) then
    raise exception 'word_siege_invalid_placements';
  end if;
  if exists (select 1 from unnest(v_indices) x where x not between 0 and 80) then
    raise exception 'word_siege_invalid_cell';
  end if;
  if exists (
    select 1 from unnest(v_rack_indices) x
    where x < 0 or x >= char_length(coalesce(v_rack, ''))
  ) then raise exception 'word_siege_invalid_rack_tile'; end if;
  select count(distinct x)::integer into v_distinct from unnest(v_indices) x;
  if v_distinct <> cardinality(v_indices) then raise exception 'word_siege_duplicate_cell'; end if;
  select count(distinct x)::integer into v_distinct from unnest(v_rack_indices) x;
  if v_distinct <> cardinality(v_rack_indices) then raise exception 'word_siege_duplicate_rack_tile'; end if;

  foreach v_index in array v_indices loop
    if (v_board -> v_index ->> 'letter') is not null then
      raise exception 'word_siege_cell_occupied';
    end if;
  end loop;

  v_anchor := v_indices[1];
  if cardinality(v_indices) > 1 then
    if p_horizontal and exists (select 1 from unnest(v_indices) x where x / 9 <> v_anchor / 9) then
      raise exception 'word_siege_not_in_one_row';
    end if;
    if not p_horizontal and exists (select 1 from unnest(v_indices) x where x % 9 <> v_anchor % 9) then
      raise exception 'word_siege_not_in_one_column';
    end if;
  end if;

  v_main_cells := private.word_siege_collect_cells_v1(
    v_board, p_placements, v_rack, v_anchor, case when p_horizontal then 1 else 9 end
  );
  if exists (select 1 from unnest(v_indices) x where not (x = any(v_main_cells))) then
    raise exception 'word_siege_gap_between_tiles';
  end if;

  select exists (
    select 1 from jsonb_array_elements(v_board) cell where cell ->> 'letter' is not null
  ) into v_existing;
  if not v_existing and not (40 = any(v_indices)) then
    raise exception 'word_siege_first_word_must_cover_center';
  end if;
  if v_existing and exists (
    select 1 from unnest(v_main_cells) x where (v_board -> x ->> 'letter') is not null
  ) then v_connected := true; end if;

  if cardinality(v_main_cells) > 1 then
    v_word := private.word_siege_word_from_cells_v1(v_board, p_placements, v_rack, v_main_cells);
    if not private.word_siege_word_allowed_v1(v_word, r.language) then
      raise exception 'word_siege_invalid_word:%', v_word;
    end if;
    v_words := array_append(v_words, v_word);
    v_primary := v_word;
    v_score := v_score + private.word_siege_score_word_v1(v_board, p_placements, v_rack, v_main_cells);
    foreach v_index in array v_main_cells loop
      v_cell := v_board -> v_index;
      if (v_cell ->> 'letter') is not null
         and coalesce((v_cell ->> 'owner')::integer, 0) not in (0, v_owner) then
        v_board := jsonb_set(
          v_board, array[v_index::text],
          v_cell || jsonb_build_object('owner', v_owner), false
        );
        v_captured := array_append(v_captured, v_index);
      end if;
    end loop;
  end if;

  foreach v_index in array v_indices loop
    v_cross_cells := private.word_siege_collect_cells_v1(
      v_board, p_placements, v_rack, v_index, case when p_horizontal then 9 else 1 end
    );
    if cardinality(v_cross_cells) > 1 then
      v_connected := v_connected or v_existing;
      v_word := private.word_siege_word_from_cells_v1(v_board, p_placements, v_rack, v_cross_cells);
      if not private.word_siege_word_allowed_v1(v_word, r.language) then
        raise exception 'word_siege_invalid_word:%', v_word;
      end if;
      v_words := array_append(v_words, v_word);
      if v_primary is null then v_primary := v_word; end if;
      v_score := v_score + private.word_siege_score_word_v1(v_board, p_placements, v_rack, v_cross_cells);
      foreach v_i in array v_cross_cells loop
        v_cell := v_board -> v_i;
        if (v_cell ->> 'letter') is not null
           and coalesce((v_cell ->> 'owner')::integer, 0) not in (0, v_owner)
           and not (v_i = any(v_captured)) then
          v_board := jsonb_set(
            v_board, array[v_i::text],
            v_cell || jsonb_build_object('owner', v_owner), false
          );
          v_captured := array_append(v_captured, v_i);
        end if;
      end loop;
    end if;
  end loop;

  if cardinality(v_words) = 0 then raise exception 'word_siege_word_required'; end if;
  if v_existing and not v_connected then raise exception 'word_siege_move_must_connect'; end if;

  for v_i in 1..cardinality(v_indices) loop
    v_index := v_indices[v_i];
    v_letter := substring(v_rack from (v_rack_indices[v_i] + 1) for 1);
    v_cell := v_board -> v_index;
    v_board := jsonb_set(
      v_board, array[v_index::text],
      v_cell || jsonb_build_object(
        'letter', v_letter, 'owner', v_owner, 'bonus_used', true
      ), false
    );
    v_placed := v_placed || jsonb_build_array(
      jsonb_build_object('index', v_index, 'letter', v_letter, 'owner', v_owner)
    );
  end loop;

  select coalesce(string_agg(substring(v_rack from (i + 1) for 1), '' order by i), '')
  into v_remaining
  from generate_series(0, char_length(v_rack) - 1) i
  where not (i = any(v_rack_indices));
  v_needed := greatest(0, 7 - char_length(v_remaining));
  v_draw := substring(v_bag from 1 for v_needed);
  v_next_rack := v_remaining || v_draw;
  v_bag := substring(v_bag from (char_length(v_draw) + 1));

  select count(*) filter (where coalesce((cell ->> 'owner')::integer, 0) = 1)::integer,
         count(*) filter (where coalesce((cell ->> 'owner')::integer, 0) = 2)::integer
  into v_one_area, v_two_area
  from jsonb_array_elements(v_board) cell;

  update public.word_siege_games
  set board = v_board,
      bag = v_bag,
      player_one_rack = case when v_owner = 1 then v_next_rack else player_one_rack end,
      player_two_rack = case when v_owner = 2 then v_next_rack else player_two_rack end,
      player_one_word_score = player_one_word_score + case when v_owner = 1 then v_score else 0 end,
      player_two_word_score = player_two_word_score + case when v_owner = 2 then v_score else 0 end,
      player_one_area = v_one_area,
      player_two_area = v_two_area,
      current_player_id = v_other,
      consecutive_passes = 0,
      move_count = move_count + 1,
      last_action = 'word:' || v_primary,
      last_action_player_id = v_uid,
      last_move_at = now(),
      updated_at = now()
  where id = r.id
  returning * into r;

  insert into public.word_siege_moves(
    game_id, player_id, primary_word, formed_words, placed_tiles, word_score, captured_cells
  ) values (
    r.id, v_uid, v_primary, v_words, v_placed, v_score, cardinality(v_captured)
  );

  if r.bag = '' and v_next_rack = '' then
    r := private.finish_word_siege_game_v1(r.id, 'rack_empty', null);
  end if;
  return r;
end
$$;

create or replace function private.pass_word_siege_turn_v1(p_game_id uuid)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_other uuid;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;
  if r.current_player_id <> v_uid then raise exception 'word_siege_not_your_turn'; end if;
  v_other := case when v_uid = r.player_one_id then r.player_two_id else r.player_one_id end;
  update public.word_siege_games
  set current_player_id = v_other,
      consecutive_passes = least(2, consecutive_passes + 1),
      move_count = move_count + 1,
      last_action = 'pass', last_action_player_id = v_uid,
      last_move_at = now(), updated_at = now()
  where id = r.id
  returning * into r;
  if r.consecutive_passes >= 2 then
    r := private.finish_word_siege_game_v1(r.id, 'consecutive_passes', null);
  end if;
  return r;
end
$$;

create or replace function private.exchange_word_siege_tiles_v1(
  p_game_id uuid,
  p_rack_indices jsonb
)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_owner integer;
  v_other uuid;
  v_rack text;
  v_indices integer[];
  v_count integer;
  v_distinct integer;
  v_remaining text;
  v_returned text;
  v_draw text;
  v_new_bag text;
  v_new_rack text;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  if p_rack_indices is null or jsonb_typeof(p_rack_indices) <> 'array'
     or jsonb_array_length(p_rack_indices) not between 1 and 7 then
    raise exception 'word_siege_invalid_exchange';
  end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;
  if r.current_player_id <> v_uid then raise exception 'word_siege_not_your_turn'; end if;
  v_owner := case when v_uid = r.player_one_id then 1 else 2 end;
  v_other := case when v_owner = 1 then r.player_two_id else r.player_one_id end;
  v_rack := case when v_owner = 1 then r.player_one_rack else r.player_two_rack end;
  select array_agg((e #>> '{}')::integer order by ordinality)
  into v_indices
  from jsonb_array_elements(p_rack_indices) with ordinality as x(e, ordinality);
  v_count := cardinality(v_indices);
  if exists (select 1 from unnest(v_indices) x where x < 0 or x >= char_length(v_rack)) then
    raise exception 'word_siege_invalid_rack_tile';
  end if;
  select count(distinct x)::integer into v_distinct from unnest(v_indices) x;
  if v_distinct <> v_count then raise exception 'word_siege_duplicate_rack_tile'; end if;
  if char_length(r.bag) < v_count then raise exception 'word_siege_not_enough_tiles'; end if;

  select coalesce(string_agg(substring(v_rack from (i + 1) for 1), '' order by i), '')
  into v_remaining
  from generate_series(0, char_length(v_rack) - 1) i
  where not (i = any(v_indices));
  select coalesce(string_agg(substring(v_rack from (i + 1) for 1), '' order by i), '')
  into v_returned
  from generate_series(0, char_length(v_rack) - 1) i
  where i = any(v_indices);
  v_draw := substring(r.bag from 1 for v_count);
  v_new_rack := v_remaining || v_draw;
  v_new_bag := private.word_siege_shuffle_text_v1(substring(r.bag from (v_count + 1)) || v_returned);

  update public.word_siege_games
  set bag = v_new_bag,
      player_one_rack = case when v_owner = 1 then v_new_rack else player_one_rack end,
      player_two_rack = case when v_owner = 2 then v_new_rack else player_two_rack end,
      current_player_id = v_other,
      consecutive_passes = 0,
      move_count = move_count + 1,
      last_action = 'exchange', last_action_player_id = v_uid,
      last_move_at = now(), updated_at = now()
  where id = r.id
  returning * into r;
  return r;
end
$$;

create or replace function private.forfeit_word_siege_game_v1(p_game_id uuid)
returns public.word_siege_games
language plpgsql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$
declare
  r public.word_siege_games;
  v_uid uuid := auth.uid();
  v_winner uuid;
begin
  if v_uid is null then raise exception 'word_siege_unauthorized'; end if;
  select * into r from public.word_siege_games where id = p_game_id for update;
  if r.id is null then raise exception 'word_siege_not_found'; end if;
  if v_uid not in (r.player_one_id, r.player_two_id) then raise exception 'word_siege_not_participant'; end if;
  if r.status <> 'playing' then raise exception 'word_siege_not_playing'; end if;
  v_winner := case when v_uid = r.player_one_id then r.player_two_id else r.player_one_id end;
  update public.word_siege_games
  set last_action = 'forfeit', last_action_player_id = v_uid,
      last_move_at = now(), updated_at = now()
  where id = r.id;
  return private.finish_word_siege_game_v1(r.id, 'forfeit', v_winner);
end
$$;

create or replace function public.find_or_create_word_siege_game_v1(p_language text default 'tr')
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.find_or_create_word_siege_game_v1(p_language) $$;

create or replace function public.cancel_word_siege_waiting_v1(p_game_id uuid)
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.cancel_word_siege_waiting_v1(p_game_id) $$;

create or replace function public.submit_word_siege_move_v1(
  p_game_id uuid,
  p_placements jsonb,
  p_horizontal boolean default true
)
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.submit_word_siege_move_v1(p_game_id, p_placements, p_horizontal) $$;

create or replace function public.pass_word_siege_turn_v1(p_game_id uuid)
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.pass_word_siege_turn_v1(p_game_id) $$;

create or replace function public.exchange_word_siege_tiles_v1(p_game_id uuid, p_rack_indices jsonb)
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.exchange_word_siege_tiles_v1(p_game_id, p_rack_indices) $$;

create or replace function public.forfeit_word_siege_game_v1(p_game_id uuid)
returns public.word_siege_games
language sql
security definer
set search_path = pg_catalog, public, private, pg_temp
as $$ select private.forfeit_word_siege_game_v1(p_game_id) $$;

revoke all on function private.word_siege_new_board_v1() from public, anon, authenticated;
revoke all on function private.word_siege_shuffle_text_v1(text) from public, anon, authenticated;
revoke all on function private.word_siege_new_bag_v1(text) from public, anon, authenticated;
revoke all on function private.word_siege_letter_value_v1(text) from public, anon, authenticated;
revoke all on function private.word_siege_letter_at_v1(jsonb, jsonb, text, integer) from public, anon, authenticated;
revoke all on function private.word_siege_collect_cells_v1(jsonb, jsonb, text, integer, integer) from public, anon, authenticated;
revoke all on function private.word_siege_word_from_cells_v1(jsonb, jsonb, text, integer[]) from public, anon, authenticated;
revoke all on function private.word_siege_word_allowed_v1(text, text) from public, anon, authenticated;
revoke all on function private.word_siege_score_word_v1(jsonb, jsonb, text, integer[]) from public, anon, authenticated;
revoke all on function private.finish_word_siege_game_v1(uuid, text, uuid) from public, anon, authenticated;
revoke all on function private.find_or_create_word_siege_game_v1(text) from public, anon, authenticated;
revoke all on function private.cancel_word_siege_waiting_v1(uuid) from public, anon, authenticated;
revoke all on function private.submit_word_siege_move_v1(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function private.pass_word_siege_turn_v1(uuid) from public, anon, authenticated;
revoke all on function private.exchange_word_siege_tiles_v1(uuid, jsonb) from public, anon, authenticated;
revoke all on function private.forfeit_word_siege_game_v1(uuid) from public, anon, authenticated;

revoke all on function public.find_or_create_word_siege_game_v1(text) from public, anon, authenticated;
revoke all on function public.cancel_word_siege_waiting_v1(uuid) from public, anon, authenticated;
revoke all on function public.submit_word_siege_move_v1(uuid, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.pass_word_siege_turn_v1(uuid) from public, anon, authenticated;
revoke all on function public.exchange_word_siege_tiles_v1(uuid, jsonb) from public, anon, authenticated;
revoke all on function public.forfeit_word_siege_game_v1(uuid) from public, anon, authenticated;

grant execute on function public.find_or_create_word_siege_game_v1(text) to authenticated;
grant execute on function public.cancel_word_siege_waiting_v1(uuid) to authenticated;
grant execute on function public.submit_word_siege_move_v1(uuid, jsonb, boolean) to authenticated;
grant execute on function public.pass_word_siege_turn_v1(uuid) to authenticated;
grant execute on function public.exchange_word_siege_tiles_v1(uuid, jsonb) to authenticated;
grant execute on function public.forfeit_word_siege_game_v1(uuid) to authenticated;
